# 기본 설정

라이브러리 import

In [1]:
import pandas as pd
import numpy as np
import os
from pprint import pprint
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score
)
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import random
import torch
import warnings


# stratify k fold 적용
from sklearn.model_selection import StratifiedKFold
from collections import Counter
import numpy as np
import pandas as pd
from imblearn.over_sampling import SMOTE, RandomOverSampler
from imblearn.combine import SMOTEENN, SMOTETomek
from collections import Counter
warnings.filterwarnings("ignore")

랜덤시드 고정

In [2]:
RANDOM_STATE = 736665
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(RANDOM_STATE)

seed_everything(RANDOM_STATE)

## 데이터 불러오기

In [3]:
train = pd.read_csv('./data/train.csv').drop(columns=['ID'])
test = pd.read_csv('./data/test.csv').drop(columns=['ID'])
print(train.shape, test.shape)

(256351, 68) (90067, 67)

# 데이터 전처리

In [4]:
# 한 컬럼에 값이 하나이며 결측치가 없는 열 제거
del_col = []
for col in train.columns:
    if train[col].nunique() == 1:
        if train[col].isnull().sum() == 0:
            print(train[col].value_counts())
            print('결측치 개수 :', train[col].isnull().sum())
            del_col.append(col)
del_col

불임 원인 - 여성 요인
0    256351
Name: count, dtype: int64
결측치 개수 : 0

['불임 원인 - 여성 요인']

In [5]:
# 전부 결측치인 열 제거 
for col in train.columns:
    if train[col].notnull().sum() == 0:
        del_col.append(col)
del_col

['불임 원인 - 여성 요인']

In [6]:
train.drop(columns=del_col, inplace=True)
test.drop(columns=del_col, inplace=True)
train.shape, test.shape

((256351, 67), (90067, 66))

### 결측치 처리

In [7]:
temp = pd.DataFrame(train.isnull().sum(), columns=['결측치 개수'])
temp = temp[temp['결측치 개수'] > 0]
temp['결측치 비율'] = temp['결측치 개수'] / train.shape[0] * 100
temp

                       결측치 개수     결측치 비율
임신 시도 또는 마지막 임신 경과 연수  246981  96.344855
특정 시술 유형                    2   0.000780
단일 배아 이식 여부              6291   2.454057
착상 전 유전 검사 사용 여부       253633  98.939735
착상 전 유전 진단 사용 여부         6291   2.454057
배아 생성 주요 이유              6291   2.454057
총 생성 배아 수                6291   2.454057
미세주입된 난자 수               6291   2.454057
미세주입에서 생성된 배아 수          6291   2.454057
이식된 배아 수                 6291   2.454057
미세주입 배아 이식 수             6291   2.454057
저장된 배아 수                 6291   2.454057
미세주입 후 저장된 배아 수          6291   2.454057
해동된 배아 수                 6291   2.454057
해동 난자 수                  6291   2.454057
수집된 신선 난자 수              6291   2.454057
저장된 신선 난자 수              6291   2.454057
혼합된 난자 수                 6291   2.454057
파트너 정자와 혼합된 난자 수         6291   2.454057
기증자 정자와 혼합된 난자 수         6291   2.454057
동결 배아 사용 여부              6291   2.454057
신선 배아 사용 여부              6291   2.454057
기증 배아 사용 여부              6291   2.454057
대리모 여부                   6291   2.454057
PGD 시술 여부              254172  99.149994
PGS 시술 여부              254422  99.247516
난자 채취 경과일               57488  22.425503
난자 해동 경과일              254915  99.439831
난자 혼합 경과일               53735  20.961494
배아 이식 경과일               43566  16.994667
배아 해동 경과일              215982  84.252451

In [8]:
## 결측치 처리
to_zero_columns = []
train[to_zero_columns] = train[to_zero_columns].fillna(0)
test[to_zero_columns] = test[to_zero_columns].fillna(0)


to_minus_columns = ['난자 채취 경과일']
train[to_minus_columns] = train[to_minus_columns].fillna(-1)
test[to_minus_columns] = test[to_minus_columns].fillna(-1)


to_one_columns = []
train[to_one_columns] = train[to_one_columns].fillna(1)
test[to_one_columns] = test[to_one_columns].fillna(1)


to_drop_columns = ['임신 시도 또는 마지막 임신 경과 연수', '난자 해동 경과일', '배아 해동 경과일']
train = train.drop(columns=to_drop_columns)
test = test.drop(columns=to_drop_columns)

to_mean_columns = ['배아 이식 경과일', '난자 혼합 경과일']
train[to_mean_columns] = train[to_mean_columns].fillna(train[to_mean_columns].mean())
test[to_mean_columns] = test[to_mean_columns].fillna(train[to_mean_columns].mean())


train['특정 시술 유형'].fillna(train['특정 시술 유형'].value_counts().index[0], inplace=True)
test['특정 시술 유형'].fillna(train['특정 시술 유형'].value_counts().index[0], inplace=True)

train.isnull().sum().sum(), test.isnull().sum().sum()

(894338, 313512)

In [9]:
# PGD 시술 여부 또는 PGS 시술 여부가 1이면 착상 전 유전 검사 사용 여부도 1로 설정하는 함수
def update_preimplantation_testing(df):
    df.loc[(df["착상 전 유전 진단 사용 여부"] == 1), "PGD 시술 여부"] = 1
    df.loc[(df["PGD 시술 여부"] == 1), "착상 전 유전 진단 사용 여부"] = 1
    df.loc[((df["착상 전 유전 검사 사용 여부"] == 1) & (df["PGD 시술 여부"].isna())), "PGS 시술 여부"] = 1
    return df

# train 및 test 데이터프레임 전처리 적용
train = update_preimplantation_testing(train)
test = update_preimplantation_testing(test)
train.isnull().sum().sum(), test.isnull().sum().sum()

(892558, 312901)

In [10]:
for col in temp[temp['결측치 개수'] == 6291].index:
    if train[col].dtype == 'object':
        train[col].fillna('DI_알 수 없음', inplace=True)
        test[col].fillna('DI_알 수 없음', inplace=True)

    elif train[col].nunique() == 2:
        train[col].fillna(train[col].mode()[0], inplace=True)
        test[col].fillna(train[col].mode()[0], inplace=True)

    else:
        train[col] = train[col].fillna(train[col].mean())
        test[col] = test[col].fillna(train[col].mean())
        
train.isnull().sum().sum(), test.isnull().sum().sum()

(760447, 267205)

In [11]:
temp = pd.DataFrame(train.isnull().sum(), columns=['결측치 개수'])
temp = temp[temp['결측치 개수'] > 0]
temp['결측치 비율'] = temp['결측치 개수'] / train.shape[0] * 100
temp

                  결측치 개수     결측치 비율
착상 전 유전 검사 사용 여부  253633  98.939735
PGD 시술 여부         253155  98.753272
PGS 시술 여부         253659  98.949877

In [12]:
to_drop_columns = ['착상 전 유전 검사 사용 여부', 'PGD 시술 여부', 'PGS 시술 여부']
train = train.drop(columns=to_drop_columns)
test = test.drop(columns=to_drop_columns)
train.isnull().sum().sum(), test.isnull().sum().sum()

(0, 0)

### 범주형 변수 인코딩

In [13]:
convert_dict1 = {'0회': 0, '1회': 1, '2회': 2, '3회': 3, '4회': 4, '5회': 5, '6회 이상': 6}

# 변환할 컬럼 리스트
columns_to_convert1 = [
    "총 시술 횟수", "클리닉 내 총 시술 횟수", "IVF 시술 횟수", "DI 시술 횟수",
    "총 임신 횟수", "IVF 임신 횟수", "DI 임신 횟수",
    "총 출산 횟수", "IVF 출산 횟수", "DI 출산 횟수"]

# 변환 딕셔너리 생성
convert_dict2 = {'만18-34세' : 26, '만35-37세' : 36, '만38-39세' : 39, '만40-42세' : 41, '만43-44세' : 44,
                 '만45-50세' : 48, '알 수 없음' : -1}

# 변환할 컬럼 리스트
columns_to_convert2 = ["시술 당시 나이"]

convert_dict3 = {'만20세 이하' : 20, '만21-25세' : 23, '만26-30세' : 28, '만31-35세' : 33,
                 '만36-40세' : 38, '만41-45세' : 43, '알 수 없음' : -1}

# 변환할 컬럼 리스트
columns_to_convert3 = ["난자 기증자 나이", "정자 기증자 나이"]

In [14]:
train[columns_to_convert1] = train[columns_to_convert1].replace(convert_dict1)
test[columns_to_convert1] = test[columns_to_convert1].replace(convert_dict1)

train[columns_to_convert2] = train[columns_to_convert2].replace(convert_dict2)
test[columns_to_convert2] = test[columns_to_convert2].replace(convert_dict2)

train[columns_to_convert3] = train[columns_to_convert3].replace(convert_dict3)
test[columns_to_convert3] = test[columns_to_convert3].replace(convert_dict3)

In [15]:
categorical_columns = train.select_dtypes(include='object').columns
categorical_columns

Index(['시술 시기 코드', '시술 유형', '특정 시술 유형', '배란 유도 유형', '배아 생성 주요 이유', '난자 출처',
       '정자 출처'],
      dtype='object')

In [16]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder(handle_unknown='ignore')
train_encoded = train.copy()
test_encoded = test.copy()

# 원핫 인코딩 적용
train_encoded_array = onehot_encoder.fit_transform(train[categorical_columns])
test_encoded_array = onehot_encoder.transform(test[categorical_columns])

# 새로운 DataFrame으로 변환
train_encoded_df = pd.DataFrame(train_encoded_array.toarray(), columns=onehot_encoder.get_feature_names_out(categorical_columns), index=train.index) # Changed to toarray()
test_encoded_df = pd.DataFrame(test_encoded_array.toarray(), columns=onehot_encoder.get_feature_names_out(categorical_columns), index=test.index) # Changed to toarray()

# 기존 데이터에서 범주형 컬럼 제거 후 원핫 인코딩된 데이터 추가
train_encoded = train.drop(columns=categorical_columns).join(train_encoded_df)
test_encoded = test.drop(columns=categorical_columns).join(test_encoded_df)
train_encoded.shape, test_encoded.shape

((256351, 112), (90067, 111))

In [17]:
import re
train_encoded.columns = [re.sub(r'[^\w\s]', '_', col) for col in train_encoded.columns]
test_encoded.columns = [re.sub(r'[^\w\s]', '_', col) for col in test_encoded.columns]

# 모델링

### 샘플링 실험

In [18]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

# train_data에서 임신 성공 여부을 제외한 모든 열을 feature로 사용
X = train_encoded.drop(columns=["임신 성공 여부"])
y = train_encoded["임신 성공 여부"]

# train 데이터를 5개로 나누어 교차 검증
under_ratio_df = pd.DataFrame(columns=["ratio", 'fold', "model", 'auc'])

ratio = 'default'
for i, index in enumerate(skf.split(X, y)):
    # 데이터 분할
    print(f"{ratio}, Fold {i + 1}")
    X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
    y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
    print(Counter(y_train), Counter(y_val))

    print('모델 학습 진행')
    class_counts = Counter(y_train)
    negative_count = class_counts[0]  # 음성 클래스 (보통 0)
    positive_count = class_counts[1]  # 양성 클래스 (보통 1)

    # 클래스 불균형 비율 계산
    class_imbalance_ratio = negative_count / positive_count if positive_count > 0 else 1
    import xgboost as xgb
    import lightgbm as lgb
    import catboost as cat
    xgb = xgb.XGBClassifier(random_state=RANDOM_STATE, scale_pos_weight=class_imbalance_ratio)
    lgbm = lgb.LGBMClassifier(random_state=RANDOM_STATE, is_unbalance=True, verbose=-1)
    cat = cat.CatBoostClassifier(verbose=0, random_state=RANDOM_STATE, auto_class_weights="Balanced")
    for model in [xgb, lgbm]:
        print(model.__class__.__name__)
        model.fit(X_train, y_train)

        y_proba = model.predict_proba(X_val)[:, 1]
        auc = roc_auc_score(y_val, y_proba)

        under_ratio_df.loc[len(under_ratio_df), :] = [ratio, i+1, model.__class__.__name__, auc]

for ratio in range(1, 3):
    normal_ratio = ratio

    for i, index in enumerate(skf.split(X, y)):
        # 데이터 분할
        print(f"{ratio}, Fold {i + 1}")
        X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
        y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
        print(Counter(y_train), Counter(y_val))

        train = pd.concat([X_train, y_train], axis=1)
        val = pd.concat([X_val, y_val], axis=1)

        df_normal = train[train["임신 성공 여부"] == 0]
        df_abnormal = train[train["임신 성공 여부"] == 1]
        print(f"Total: Normal: {len(df_normal)}, AbNormal: {len(df_abnormal)}")

        df_normal = df_normal.sample(n=int(len(df_abnormal) * normal_ratio), replace=False, random_state=RANDOM_STATE)
        df_concat = pd.concat([df_normal, df_abnormal], axis=0).reset_index(drop=True)
        X_under, y_under = df_concat.drop(columns=["임신 성공 여부"]), df_concat["임신 성공 여부"]

        print("언더샘플링 후 train의 클래스 비율:", Counter(y_under))

        print('모델 학습 진행')
        class_counts = Counter(y_under)
        negative_count = class_counts[0]  # 음성 클래스 (보통 0)
        positive_count = class_counts[1]  # 양성 클래스 (보통 1)

        # 클래스 불균형 비율 계산
        class_imbalance_ratio = negative_count / positive_count if positive_count > 0 else 1
        import xgboost as xgb
        import lightgbm as lgb
        import catboost as cat
        xgb = xgb.XGBClassifier(random_state=RANDOM_STATE, scale_pos_weight=class_imbalance_ratio)
        lgbm = lgb.LGBMClassifier(random_state=RANDOM_STATE, is_unbalance=True, verbose=-1)
        cat = cat.CatBoostClassifier(verbose=0, random_state=RANDOM_STATE, auto_class_weights="Balanced")
        for model in [xgb, lgbm]:
            print(model.__class__.__name__)
            model.fit(X_under, y_under)

            y_proba = model.predict_proba(X_val)[:, 1]
            auc = roc_auc_score(y_val, y_proba)
          
            under_ratio_df.loc[len(under_ratio_df), :] = [ratio, i+1, model.__class__.__name__, auc]


ratio = 'ros'
for i, index in enumerate(skf.split(X, y)):
    # 데이터 분할
    print(f"{ratio}, Fold {i + 1}")
    X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
    y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
    print(Counter(y_train), Counter(y_val))

    ros = RandomOverSampler(random_state=RANDOM_STATE)
    X_ros, y_ros = ros.fit_resample(X_train, y_train)
    print("Random Oversampling 클래스 비율:", Counter(y_ros))
    print('모델 학습 진행')
    class_counts = Counter(y_ros)
    negative_count = class_counts[0]  # 음성 클래스 (보통 0)
    positive_count = class_counts[1]  # 양성 클래스 (보통 1)

    # 클래스 불균형 비율 계산
    class_imbalance_ratio = negative_count / positive_count if positive_count > 0 else 1
    import xgboost as xgb
    import lightgbm as lgb
    import catboost as cat
    xgb = xgb.XGBClassifier(random_state=RANDOM_STATE, scale_pos_weight=class_imbalance_ratio)
    lgbm = lgb.LGBMClassifier(random_state=RANDOM_STATE, is_unbalance=True, verbose=-1)
    cat = cat.CatBoostClassifier(verbose=0, random_state=RANDOM_STATE, auto_class_weights="Balanced")

    for model in [xgb, lgbm]:
        print(model.__class__.__name__)
        model.fit(X_ros, y_ros)

        y_proba = model.predict_proba(X_val)[:, 1]
        auc = roc_auc_score(y_val, y_proba)

        under_ratio_df.loc[len(under_ratio_df), :] = [ratio, i+1, model.__class__.__name__, auc]

default, Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
모델 학습 진행
XGBClassifier
LGBMClassifier
default, Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
모델 학습 진행
XGBClassifier
LGBMClassifier
default, Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
모델 학습 진행
XGBClassifier
LGBMClassifier
default, Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
모델 학습 진행
XGBClassifier
LGBMClassifier
default, Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
모델 학습 진행
XGBClassifier
LGBMClassifier
1, Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
Total: Normal: 152098, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 52982, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
1, Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Total: Normal: 152098, AbNormal: 52983
언더샘플링 후 train의 클래스 비율: Counter({0: 52983, 1: 52983})
모델 학습 진행
XGBClassifier
LGBMClassifier
1, Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Total: Normal: 152098, AbNormal: 52983
언더샘플링 후 train의 클래스 비율: Counter({0: 52983, 1: 52983})
모델 학습 진행
XGBClassifier
LGBMClassifier
1, Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Total: Normal: 152099, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 52982, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
1, Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Total: Normal: 152099, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 52982, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
2, Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
Total: Normal: 152098, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 105964, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
2, Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Total: Normal: 152098, AbNormal: 52983
언더샘플링 후 train의 클래스 비율: Counter({0: 105966, 1: 52983})
모델 학습 진행
XGBClassifier
LGBMClassifier
2, Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Total: Normal: 152098, AbNormal: 52983
언더샘플링 후 train의 클래스 비율: Counter({0: 105966, 1: 52983})
모델 학습 진행
XGBClassifier
LGBMClassifier
2, Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Total: Normal: 152099, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 105964, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
2, Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Total: Normal: 152099, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 105964, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
ros, Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
Random Oversampling 클래스 비율: Counter({0: 152098, 1: 152098})
모델 학습 진행
XGBClassifier
LGBMClassifier
ros, Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Random Oversampling 클래스 비율: Counter({0: 152098, 1: 152098})
모델 학습 진행
XGBClassifier
LGBMClassifier
ros, Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Random Oversampling 클래스 비율: Counter({0: 152098, 1: 152098})
모델 학습 진행
XGBClassifier
LGBMClassifier
ros, Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Random Oversampling 클래스 비율: Counter({0: 152099, 1: 152099})
모델 학습 진행
XGBClassifier
LGBMClassifier
ros, Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Random Oversampling 클래스 비율: Counter({0: 152099, 1: 152099})
모델 학습 진행
XGBClassifier
LGBMClassifier

In [19]:
under_ratio_df.groupby(["ratio", "model"]).mean()[['auc']]

                             auc
ratio   model
1       LGBMClassifier   0.73778
        XGBClassifier   0.733022
2       LGBMClassifier   0.73852
        XGBClassifier   0.734382
default LGBMClassifier  0.738864
        XGBClassifier   0.735134
ros     LGBMClassifier  0.738255
        XGBClassifier   0.734634

In [20]:
under_ratio_df.groupby(["ratio", "model"]).mean()[['auc']].sort_values(by='auc', ascending=False).head()

                             auc
ratio   model
default LGBMClassifier  0.738864
2       LGBMClassifier   0.73852
ros     LGBMClassifier  0.738255
1       LGBMClassifier   0.73778
default XGBClassifier   0.735134

In [21]:
under_ratio_df.groupby(["ratio"])[['auc']].mean().sort_values(by='auc', ascending=False)

              auc
ratio
default  0.736999
2        0.736451
ros      0.736444
1        0.735401

In [22]:
top5_df = under_ratio_df.groupby(["ratio", "model"]).mean()[['auc']].sort_values(by='auc', ascending=False).head()
top5_df.reset_index(inplace=True)
top5_df

     ratio           model       auc
0  default  LGBMClassifier  0.738864
1        2  LGBMClassifier   0.73852
2      ros  LGBMClassifier  0.738255
3        1  LGBMClassifier   0.73778
4  default   XGBClassifier  0.735134

#### 하이퍼 파라미터 튜닝

In [23]:
import optuna

# train_data에서 임신 성공 여부을 제외한 모든 열을 feature로 사용
X = train_encoded.drop(columns=["임신 성공 여부"])
y = train_encoded["임신 성공 여부"]

# Optuna objective function
def objective(trial, ratio, model_name):

    # Stratified KFold Cross Validation
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
    auc_scores = []
    for i, index in enumerate(skf.split(X, y)):
        X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
        y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
        train = pd.concat([X_train, y_train], axis=1)
        val = pd.concat([X_val, y_val], axis=1)
        if ratio == 'default':
            X_train_sample, y_train_sample = X_train, y_train

        elif ratio == 'ros':
            ros = RandomOverSampler(random_state=RANDOM_STATE)
            X_ros, y_ros = ros.fit_resample(X_train, y_train)
            X_train_sample, y_train_sample = X_ros, y_ros 

        elif ratio == 'smote':
            smote = SMOTE(sampling_strategy=0.7, random_state=RANDOM_STATE)
            X_smote, y_smote = smote.fit_resample(X_train, y_train)
            X_train_sample, y_train_sample = X_smote, y_smote

        else:
            normal_ratio = ratio
            df_normal = train[train["임신 성공 여부"] == 0]
            df_abnormal = train[train["임신 성공 여부"] == 1]

            df_normal = df_normal.sample(n=int(len(df_abnormal) * normal_ratio), replace=False, random_state=RANDOM_STATE)
            df_concat = pd.concat([df_normal, df_abnormal], axis=0).reset_index(drop=True)
            X_train_sample, y_train_sample = df_concat.drop(columns=["임신 성공 여부"]), df_concat["임신 성공 여부"]


        if model_name == 'XGBClassifier':
            param = {
                'objective': 'binary:logistic',
                'eval_metric': 'auc',
                'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.1),  # 학습률 범위 좁힘
                'max_depth': trial.suggest_int('max_depth', 3, 7),  # max_depth 범위 좁힘
                'min_child_weight': trial.suggest_loguniform('min_child_weight', 1e-2, 5),  # 최소 가중치 범위 좁힘
                'subsample': trial.suggest_uniform('subsample', 0.6, 0.9),  # 샘플 비율 범위 좁힘
                'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 0.9),  # 특성 비율 범위 좁힘
                'lambda': trial.suggest_loguniform('lambda', 1e-3, 1.0),  # L2 정규화 범위 좁힘
                'alpha': trial.suggest_loguniform('alpha', 1e-3, 1.0),  # L1 정규화 범위 좁힘
                'n_estimators': trial.suggest_int('n_estimators', 500, 5000),
                'scale_pos_weight': trial.suggest_loguniform('scale_pos_weight', 1, 5),  # 불균형 클래스 가중치 범위 좁힘
                'gamma': trial.suggest_uniform('gamma', 0, 3),  # 트리 분할 시 최소 손실 감소값 범위 좁힘
                'max_delta_step': trial.suggest_int('max_delta_step', 0, 5)  # 과적합 방지 범위 좁힘
            }

            model = xgb.XGBClassifier(**param, random_state=RANDOM_STATE, n_jobs=-1)

        elif model_name == 'LGBMClassifier':
            param = {
                'objective': 'binary',
                'metric': 'auc',
                'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),  # 학습률 범위 확장
                'num_leaves': trial.suggest_int('num_leaves', 20, 80),  # num_leaves 범위 확장
                'max_depth': trial.suggest_int('max_depth', 3, 10),  # max_depth 범위 확장
                'min_child_samples': trial.suggest_int('min_child_samples', 10, 150),  # 최소 샘플 수 범위 확장
                'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),  # 샘플링 비율 범위 확장
                'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.5, 1.0),  # 특성 비율 범위 확장
                'lambda_l1': trial.suggest_loguniform('lambda_l1', 1e-4, 10),  # L1 정규화 범위 확장
                'lambda_l2': trial.suggest_loguniform('lambda_l2', 1e-4, 2.0),  # L2 정규화 범위 확장
                'max_bin': trial.suggest_int('max_bin', 100, 600),  # bin 수 범위 확장
                'n_estimators': trial.suggest_int('n_estimators', 500, 6000),  # n_estimators 범위 확장
                'scale_pos_weight': trial.suggest_loguniform('scale_pos_weight', 0.5, 5),  # 클래스 불균형 조정
                'min_child_weight': trial.suggest_loguniform('min_child_weight', 1e-3, 5),  # 최소 가중치 범위 확장
                'feature_fraction': trial.suggest_uniform('feature_fraction', 0.5, 1.0),  # 특성 비율 범위 확장
                'bagging_fraction': trial.suggest_uniform('bagging_fraction', 0.5, 1.0),  # 배깅 샘플링 비율 범위 확장
                'bagging_freq': trial.suggest_int('bagging_freq', 1, 7)  # 배깅 적용 주기 범위 확장
            }

            # param = {
            #     'objective': 'binary',
            #     'metric': 'auc',
            #     'learning_rate': trial.suggest_loguniform('learning_rate', 0.001, 0.05),  
            #     'num_leaves': trial.suggest_int('num_leaves', 31, 127),  
            #     'max_depth': trial.suggest_int('max_depth', 4, 12),  
            #     'min_child_samples': trial.suggest_int('min_child_samples', 10, 120),  
            #     'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.7, 0.9),  
            #     'lambda_l1': trial.suggest_loguniform('lambda_l1', 1e-3, 5),  
            #     'lambda_l2': trial.suggest_loguniform('lambda_l2', 1e-3, 1.0),  
            #     'max_bin': trial.suggest_int('max_bin', 200, 500),  
            #     'n_estimators': trial.suggest_int('n_estimators', 1000, 8000),  
            #     'scale_pos_weight': trial.suggest_loguniform('scale_pos_weight', 1.0, 3.5),  
            #     'min_child_weight': trial.suggest_loguniform('min_child_weight', 1e-2, 10),  
            #     'feature_fraction': trial.suggest_uniform('feature_fraction', 0.7, 0.9),  
            #     'bagging_fraction': trial.suggest_uniform('bagging_fraction', 0.7, 0.9),  
            #     'bagging_freq': trial.suggest_int('bagging_freq', 1, 7)
            # }


            model = lgb.LGBMClassifier(**param, random_state=RANDOM_STATE, n_jobs=-1)
            

        elif model_name == 'CatBoostClassifier':
            param = {
                'objective': 'Logloss',
                'eval_metric': 'AUC',
                'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.1),  # 학습률 범위 좁힘
                'depth': trial.suggest_int('depth', 3, 7),  # depth 범위 좁힘
                'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 5.0),  # L2 정규화 범위 좁힘
                'random_strength': trial.suggest_uniform('random_strength', 0.5, 3),  # 잡음 정도 범위 좁힘
                'bagging_temperature': trial.suggest_uniform('bagging_temperature', 0, 0.3),  # 배깅 온도 범위 좁힘
                # 'border_count': trial.suggest_int('border_count', 32, 100),  # border 수 범위 좁힘
                'colsample_bylevel': trial.suggest_uniform('colsample_bylevel', 0.6, 0.9),  # 특성 비율 범위 좁힘
                'iterations': trial.suggest_int('iterations', 500, 2000),
                # 'scale_pos_weight': trial.suggest_loguniform('scale_pos_weight', 1, 5),  # 불균형 클래스 가중치 범위 좁힘
                'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 50),  # 리프 노드 최소 데이터 수 범위 좁힘
                'max_bin': trial.suggest_int('max_bin', 100, 150)  # bin 수 범위 좁힘
            }
            model = cat.CatBoostClassifier(**param, verbose=0, random_state=RANDOM_STATE, auto_class_weights="Balanced")    

        else:
            raise ValueError("Invalid model name")
        model.fit(X_train_sample, y_train_sample)

        # 예측 및 AUC 평가
        y_prob = model.predict_proba(X_val)[:, 1]  # 클래스 1의 확률 예측
        auc = roc_auc_score(y_val, y_prob)
        auc_scores.append(auc)

    # 평균 AUC 반환 (Optuna는 최대화 목표)
    return np.mean(auc_scores)

In [24]:
import optuna

def optimize_ran(ratio, model_name):
    def objective_wrapper(trial):
        return objective(trial, ratio, model_name)
    
    # **초반에는 RandomSampler 사용 (빠른 탐색)**
    study = optuna.create_study(
        direction='maximize', 
        sampler=optuna.samplers.RandomSampler(seed=RANDOM_STATE)  # 랜덤 샘플링 시드 고정
    )
    study.optimize(objective_wrapper, n_trials=20)  # 초반 10회 랜덤 탐색

    print('Best hyperparameters: ', study.best_params, study.best_value)
    return study.best_params, study.best_value, study

params, auc, study = optimize_ran(ratio=top5_df['ratio'][0], model_name=top5_df['model'][0])
top5_df.loc[0, ['param', 'tuned_auc']] =  params, auc

import pickle

# Study 저장
with open("./data/optuna_study.pkl", "wb") as f:
    pickle.dump(study, f)

# Study 불러오기
with open("./data/optuna_study.pkl", "rb") as f:
    study = pickle.load(f)

[I 2025-02-26 09:36:59,394] A new study created in memory with name: no-name-cc14d8a5-b019-42c9-8240-434045a99c48
[I 2025-02-26 09:38:57,646] Trial 0 finished with value: 0.7338829848430737 and parameters: {'learning_rate': 0.015425143772139221, 'num_leaves': 66, 'max_depth': 9, 'min_child_samples': 133, 'subsample': 0.8653901486840079, 'colsample_bytree': 0.9983917544473779, 'lambda_l1': 0.6105295749847629, 'lambda_l2': 0.044168222863989644, 'max_bin': 126, 'n_estimators': 2273, 'scale_pos_weight': 1.95333788496361, 'min_child_weight': 0.05291362037823648, 'feature_fraction': 0.9523240386576735, 'bagging_fraction': 0.6518583351261913, 'bagging_freq': 7}. Best is trial 0 with value: 0.7338829848430737.
[I 2025-02-26 09:40:45,737] Trial 1 finished with value: 0.7333386716012593 and parameters: {'learning_rate': 0.03116375846521187, 'num_leaves': 30, 'max_depth': 10, 'min_child_samples': 56, 'subsample': 0.7221916135181802, 'colsample_bytree': 0.7974033679912669, 'lambda_l1': 0.009015009783863792, 'lambda_l2': 0.22318604907203787, 'max_bin': 309, 'n_estimators': 3278, 'scale_pos_weight': 1.1584740056323315, 'min_child_weight': 0.001135663095613767, 'feature_fraction': 0.712712879854045, 'bagging_fraction': 0.9033154902029454, 'bagging_freq': 5}. Best is trial 0 with value: 0.7338829848430737.
[I 2025-02-26 09:42:50,088] Trial 2 finished with value: 0.739536204105398 and parameters: {'learning_rate': 0.005585138038286644, 'num_leaves': 30, 'max_depth': 9, 'min_child_samples': 19, 'subsample': 0.5716200252264407, 'colsample_bytree': 0.5563822503362531, 'lambda_l1': 0.37445243392490873, 'lambda_l2': 0.03917400861968649, 'max_bin': 168, 'n_estimators': 3134, 'scale_pos_weight': 1.3761192208957074, 'min_child_weight': 0.0014322261738596, 'feature_fraction': 0.5709073409709251, 'bagging_fraction': 0.6368713177073566, 'bagging_freq': 6}. Best is trial 2 with value: 0.739536204105398.
[I 2025-02-26 09:43:49,788] Trial 3 finished with value: 0.7394851658546442 and parameters: {'learning_rate': 0.008096960834540465, 'num_leaves': 71, 'max_depth': 7, 'min_child_samples': 138, 'subsample': 0.6859298884663338, 'colsample_bytree': 0.6141613195771627, 'lambda_l1': 1.108795846523692, 'lambda_l2': 0.7882677565739042, 'max_bin': 541, 'n_estimators': 1340, 'scale_pos_weight': 4.668696941089527, 'min_child_weight': 0.3095631848544191, 'feature_fraction': 0.7817151315868243, 'bagging_fraction': 0.8898762895296095, 'bagging_freq': 1}. Best is trial 2 with value: 0.739536204105398.
[I 2025-02-26 09:44:22,965] Trial 4 finished with value: 0.73301122505916 and parameters: {'learning_rate': 0.09990956777240707, 'num_leaves': 22, 'max_depth': 9, 'min_child_samples': 113, 'subsample': 0.9551760582624331, 'colsample_bytree': 0.6872439089217708, 'lambda_l1': 1.2635997976483877, 'lambda_l2': 0.24901720148451442, 'max_bin': 262, 'n_estimators': 881, 'scale_pos_weight': 3.3053781683280863, 'min_child_weight': 0.00602996638950076, 'feature_fraction': 0.6903408973729224, 'bagging_fraction': 0.5789881028586417, 'bagging_freq': 2}. Best is trial 2 with value: 0.739536204105398.
[I 2025-02-26 09:46:50,654] Trial 5 finished with value: 0.7258418971083542 and parameters: {'learning_rate': 0.07347180751475983, 'num_leaves': 78, 'max_depth': 5, 'min_child_samples': 47, 'subsample': 0.6462960279748633, 'colsample_bytree': 0.9029742680124451, 'lambda_l1': 1.6452578296693248, 'lambda_l2': 0.2166297935943999, 'max_bin': 116, 'n_estimators': 4162, 'scale_pos_weight': 0.8034355990112857, 'min_child_weight': 0.015629967337268454, 'feature_fraction': 0.704909834669965, 'bagging_fraction': 0.7767297049533608, 'bagging_freq': 7}. Best is trial 2 with value: 0.739536204105398.
[I 2025-02-26 09:50:33,010] Trial 6 finished with value: 0.7382328181583466 and parameters: {'learning_rate': 0.007055958592362742, 'num_leaves': 75, 'max_depth': 6, 'min_child_samples': 73, 'subsample': 0.7868548396950638, 'colsample_bytree': 0.9661174751955484, 'lambda_l1': 7.510380211774199, 'lambda_l2': 0.001082515878269277, 'max_bin': 205, 'n_estimators': 5302, 'scale_pos_weight': 1.36889391346348, 'min_child_weight': 0.27082904763757115, 'feature_fraction': 0.9115005320221202, 'bagging_fraction': 0.6338247134014405, 'bagging_freq': 4}. Best is trial 2 with value: 0.739536204105398.
[I 2025-02-26 09:51:27,954] Trial 7 finished with value: 0.7361701757280315 and parameters: {'learning_rate': 0.05038051650808287, 'num_leaves': 38, 'max_depth': 5, 'min_child_samples': 115, 'subsample': 0.881223407910463, 'colsample_bytree': 0.5327622162515878, 'lambda_l1': 0.4894064145453653, 'lambda_l2': 0.012043010609013723, 'max_bin': 259, 'n_estimators': 1523, 'scale_pos_weight': 2.0812420732908947, 'min_child_weight': 0.0016081892341730456, 'feature_fraction': 0.7842528265669715, 'bagging_fraction': 0.7462220377237454, 'bagging_freq': 3}. Best is trial 2 with value: 0.739536204105398.
[I 2025-02-26 09:56:41,778] Trial 8 finished with value: 0.7081321055127546 and parameters: {'learning_rate': 0.06885482660033462, 'num_leaves': 75, 'max_depth': 10, 'min_child_samples': 21, 'subsample': 0.9069891313342352, 'colsample_bytree': 0.6153416039231351, 'lambda_l1': 3.510360536810731, 'lambda_l2': 0.006172259803263764, 'max_bin': 577, 'n_estimators': 4910, 'scale_pos_weight': 2.3375765118714305, 'min_child_weight': 0.06967565185933576, 'feature_fraction': 0.551697668559838, 'bagging_fraction': 0.8555369001730506, 'bagging_freq': 5}. Best is trial 2 with value: 0.739536204105398.
[I 2025-02-26 09:57:41,493] Trial 9 finished with value: 0.7393319502283956 and parameters: {'learning_rate': 0.00636669956943231, 'num_leaves': 44, 'max_depth': 5, 'min_child_samples': 53, 'subsample': 0.6076315564100284, 'colsample_bytree': 0.8493410264545999, 'lambda_l1': 0.24503195253374185, 'lambda_l2': 0.15906650264278605, 'max_bin': 106, 'n_estimators': 1710, 'scale_pos_weight': 0.5689494137118395, 'min_child_weight': 0.11526044723423878, 'feature_fraction': 0.6387935121225002, 'bagging_fraction': 0.996860792879829, 'bagging_freq': 1}. Best is trial 2 with value: 0.739536204105398.
[I 2025-02-26 09:59:44,751] Trial 10 finished with value: 0.7395980824208157 and parameters: {'learning_rate': 0.009472902001113578, 'num_leaves': 44, 'max_depth': 4, 'min_child_samples': 96, 'subsample': 0.9263304974726281, 'colsample_bytree': 0.9545125683629523, 'lambda_l1': 0.003983286973198198, 'lambda_l2': 0.07408975311080031, 'max_bin': 211, 'n_estimators': 1731, 'scale_pos_weight': 2.160158734295782, 'min_child_weight': 1.7815490358345771, 'feature_fraction': 0.9178770758397096, 'bagging_fraction': 0.5337384100461013, 'bagging_freq': 7}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:02:17,530] Trial 11 finished with value: 0.7359459431046945 and parameters: {'learning_rate': 0.05058616696034423, 'num_leaves': 29, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.6584970207947708, 'colsample_bytree': 0.535131601120893, 'lambda_l1': 0.001935483655522908, 'lambda_l2': 0.003266184011866186, 'max_bin': 281, 'n_estimators': 1295, 'scale_pos_weight': 0.8363173112229804, 'min_child_weight': 0.0020073395997213016, 'feature_fraction': 0.8102603222555723, 'bagging_fraction': 0.9593265845263816, 'bagging_freq': 2}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:05:00,574] Trial 12 finished with value: 0.7391135838640597 and parameters: {'learning_rate': 0.03507053331232095, 'num_leaves': 43, 'max_depth': 3, 'min_child_samples': 110, 'subsample': 0.5643007988281081, 'colsample_bytree': 0.7507367701850713, 'lambda_l1': 0.0026815604808119843, 'lambda_l2': 0.04057493655651061, 'max_bin': 290, 'n_estimators': 2475, 'scale_pos_weight': 1.5926206056622803, 'min_child_weight': 0.003797772466909962, 'feature_fraction': 0.7219512472304341, 'bagging_fraction': 0.7159709268191258, 'bagging_freq': 4}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:10:19,282] Trial 13 finished with value: 0.7308217308637645 and parameters: {'learning_rate': 0.05442765462289306, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 135, 'subsample': 0.724748777973639, 'colsample_bytree': 0.782683685963973, 'lambda_l1': 0.005871204131712403, 'lambda_l2': 0.0018639154247633543, 'max_bin': 448, 'n_estimators': 2995, 'scale_pos_weight': 1.7360946109753392, 'min_child_weight': 0.0011631477719490774, 'feature_fraction': 0.6315332289456946, 'bagging_fraction': 0.7299133053657518, 'bagging_freq': 2}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:21:01,711] Trial 14 finished with value: 0.7359408538438458 and parameters: {'learning_rate': 0.007698903333238432, 'num_leaves': 66, 'max_depth': 8, 'min_child_samples': 48, 'subsample': 0.91959244871182, 'colsample_bytree': 0.7420988472180625, 'lambda_l1': 0.00103002762919727, 'lambda_l2': 0.0003491098245162472, 'max_bin': 288, 'n_estimators': 4429, 'scale_pos_weight': 0.7362551960843415, 'min_child_weight': 0.10525773369069878, 'feature_fraction': 0.9344325613802366, 'bagging_fraction': 0.983452210859086, 'bagging_freq': 2}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:23:58,803] Trial 15 finished with value: 0.7316369856291409 and parameters: {'learning_rate': 0.07088890582916445, 'num_leaves': 52, 'max_depth': 4, 'min_child_samples': 136, 'subsample': 0.6367319035708044, 'colsample_bytree': 0.9353686317549218, 'lambda_l1': 0.0007718539662243672, 'lambda_l2': 0.001107228041242988, 'max_bin': 298, 'n_estimators': 4742, 'scale_pos_weight': 1.9304861367099717, 'min_child_weight': 0.00433391002815958, 'feature_fraction': 0.7884565104762318, 'bagging_fraction': 0.9386320443689432, 'bagging_freq': 6}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:29:28,944] Trial 16 finished with value: 0.7300137416511762 and parameters: {'learning_rate': 0.012795921009748922, 'num_leaves': 72, 'max_depth': 8, 'min_child_samples': 34, 'subsample': 0.6001639397851228, 'colsample_bytree': 0.9198694088517618, 'lambda_l1': 2.6581833255133915, 'lambda_l2': 0.029317884958132864, 'max_bin': 115, 'n_estimators': 5263, 'scale_pos_weight': 0.9943338665426116, 'min_child_weight': 0.001825347991959572, 'feature_fraction': 0.9808177912972761, 'bagging_fraction': 0.6733017651978113, 'bagging_freq': 2}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:30:01,447] Trial 17 finished with value: 0.7386066875764274 and parameters: {'learning_rate': 0.019786597841588226, 'num_leaves': 43, 'max_depth': 7, 'min_child_samples': 19, 'subsample': 0.7167829217358992, 'colsample_bytree': 0.8153855730953183, 'lambda_l1': 0.08901114713196834, 'lambda_l2': 0.11475918106759839, 'max_bin': 184, 'n_estimators': 769, 'scale_pos_weight': 4.241550779708251, 'min_child_weight': 0.019463703782270116, 'feature_fraction': 0.9051864630110871, 'bagging_fraction': 0.5946442313411389, 'bagging_freq': 5}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:32:24,284] Trial 18 finished with value: 0.728847216356787 and parameters: {'learning_rate': 0.06288155634331212, 'num_leaves': 21, 'max_depth': 5, 'min_child_samples': 148, 'subsample': 0.9019948650637313, 'colsample_bytree': 0.6996381302007002, 'lambda_l1': 0.33315171912427727, 'lambda_l2': 0.0020271308425866127, 'max_bin': 216, 'n_estimators': 4013, 'scale_pos_weight': 3.6976210284936233, 'min_child_weight': 1.283095233420513, 'feature_fraction': 0.6618374112414924, 'bagging_fraction': 0.7940054556087353, 'bagging_freq': 3}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:34:11,963] Trial 19 finished with value: 0.7310672078281494 and parameters: {'learning_rate': 0.03359729833812513, 'num_leaves': 66, 'max_depth': 10, 'min_child_samples': 45, 'subsample': 0.6830893045370803, 'colsample_bytree': 0.5293966377504692, 'lambda_l1': 0.07200906601313788, 'lambda_l2': 1.081709892322443, 'max_bin': 382, 'n_estimators': 1706, 'scale_pos_weight': 2.5954814796041226, 'min_child_weight': 0.017486270061591726, 'feature_fraction': 0.9178867323867471, 'bagging_fraction': 0.9537110904354152, 'bagging_freq': 2}. Best is trial 10 with value: 0.7395980824208157.

Best hyperparameters:  {'learning_rate': 0.009472902001113578, 'num_leaves': 44, 'max_depth': 4, 'min_child_samples': 96, 'subsample': 0.9263304974726281, 'colsample_bytree': 0.9545125683629523, 'lambda_l1': 0.003983286973198198, 'lambda_l2': 0.07408975311080031, 'max_bin': 211, 'n_estimators': 1731, 'scale_pos_weight': 2.160158734295782, 'min_child_weight': 1.7815490358345771, 'feature_fraction': 0.9178770758397096, 'bagging_fraction': 0.5337384100461013, 'bagging_freq': 7} 0.7395980824208157

In [25]:
study.optimize(lambda trial: objective(trial, top5_df['ratio'][0], top5_df['model'][0]), n_trials=30)

params, auc = study.best_params, study.best_value
print(params, auc)
top5_df.loc[0, ['param', 'tuned_auc']] =  params, auc

# Study 저장
with open("./data/optuna_study_랜덤완.pkl", "wb") as f:
    pickle.dump(study, f)

# Study 불러오기
with open("./data/optuna_study_랜덤완.pkl", "rb") as f:
    study = pickle.load(f)

[I 2025-02-26 10:37:35,018] Trial 20 finished with value: 0.733604076408731 and parameters: {'learning_rate': 0.011345626605096769, 'num_leaves': 75, 'max_depth': 9, 'min_child_samples': 46, 'subsample': 0.9159144260138378, 'colsample_bytree': 0.5909900454472763, 'lambda_l1': 0.012880736066555386, 'lambda_l2': 0.0010195141515696757, 'max_bin': 256, 'n_estimators': 3230, 'scale_pos_weight': 3.4058426081316924, 'min_child_weight': 0.043935179376647635, 'feature_fraction': 0.9855540025756568, 'bagging_fraction': 0.9855584519671904, 'bagging_freq': 4}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:42:07,224] Trial 21 finished with value: 0.7082062979721606 and parameters: {'learning_rate': 0.044194419131192854, 'num_leaves': 58, 'max_depth': 10, 'min_child_samples': 35, 'subsample': 0.8471550516588009, 'colsample_bytree': 0.7672541724132067, 'lambda_l1': 0.019368913791820087, 'lambda_l2': 0.00011058211950156807, 'max_bin': 232, 'n_estimators': 5961, 'scale_pos_weight': 3.835921696908625, 'min_child_weight': 0.6027686909784113, 'feature_fraction': 0.7590792632633852, 'bagging_fraction': 0.6321388879355188, 'bagging_freq': 7}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:44:02,878] Trial 22 finished with value: 0.7249254600503825 and parameters: {'learning_rate': 0.08274408408082157, 'num_leaves': 37, 'max_depth': 5, 'min_child_samples': 104, 'subsample': 0.500538193404521, 'colsample_bytree': 0.7293722212316055, 'lambda_l1': 0.0006243741458877048, 'lambda_l2': 0.760408576569091, 'max_bin': 438, 'n_estimators': 3604, 'scale_pos_weight': 1.9298703331419969, 'min_child_weight': 0.0013805431275077543, 'feature_fraction': 0.948611595922684, 'bagging_fraction': 0.5983867067587514, 'bagging_freq': 6}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:46:13,796] Trial 23 finished with value: 0.7358900133747293 and parameters: {'learning_rate': 0.01917025199563695, 'num_leaves': 56, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.6863174840785362, 'colsample_bytree': 0.6484642889031578, 'lambda_l1': 0.009294867312637456, 'lambda_l2': 0.016476513916362793, 'max_bin': 557, 'n_estimators': 3541, 'scale_pos_weight': 4.811064832170782, 'min_child_weight': 0.019542752600618694, 'feature_fraction': 0.8555266057879338, 'bagging_fraction': 0.742302555407246, 'bagging_freq': 3}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:48:51,302] Trial 24 finished with value: 0.7375113776350706 and parameters: {'learning_rate': 0.016092824205502492, 'num_leaves': 36, 'max_depth': 4, 'min_child_samples': 14, 'subsample': 0.9756819114235328, 'colsample_bytree': 0.6607900788607213, 'lambda_l1': 0.08202750690104336, 'lambda_l2': 1.9899376558142507, 'max_bin': 367, 'n_estimators': 5449, 'scale_pos_weight': 3.2184823167162926, 'min_child_weight': 2.4948261886684224, 'feature_fraction': 0.8525644450191505, 'bagging_fraction': 0.9350941712527876, 'bagging_freq': 7}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:49:43,456] Trial 25 finished with value: 0.735478220691945 and parameters: {'learning_rate': 0.04453108101502274, 'num_leaves': 21, 'max_depth': 7, 'min_child_samples': 94, 'subsample': 0.6727855762502507, 'colsample_bytree': 0.9764485815252452, 'lambda_l1': 0.028343288451527705, 'lambda_l2': 0.006068292762742412, 'max_bin': 273, 'n_estimators': 1653, 'scale_pos_weight': 4.828963400646951, 'min_child_weight': 0.004694980581985508, 'feature_fraction': 0.7492837420258035, 'bagging_fraction': 0.7093962705478856, 'bagging_freq': 7}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:52:17,583] Trial 26 finished with value: 0.7259528513686162 and parameters: {'learning_rate': 0.0715445311961556, 'num_leaves': 32, 'max_depth': 5, 'min_child_samples': 42, 'subsample': 0.6031489153566904, 'colsample_bytree': 0.6193300563458408, 'lambda_l1': 0.020178354157555634, 'lambda_l2': 0.04510431019651522, 'max_bin': 237, 'n_estimators': 3436, 'scale_pos_weight': 2.4352554020456494, 'min_child_weight': 0.024498106082877665, 'feature_fraction': 0.985855061199002, 'bagging_fraction': 0.9046599056382517, 'bagging_freq': 2}. Best is trial 10 with value: 0.7395980824208157.
[I 2025-02-26 10:55:02,147] Trial 27 finished with value: 0.7396130913924788 and parameters: {'learning_rate': 0.005259047845727506, 'num_leaves': 20, 'max_depth': 3, 'min_child_samples': 111, 'subsample': 0.7551797664352489, 'colsample_bytree': 0.5129156297801307, 'lambda_l1': 0.0011826620675187561, 'lambda_l2': 0.03547199696039481, 'max_bin': 402, 'n_estimators': 5292, 'scale_pos_weight': 1.324502800720647, 'min_child_weight': 0.0015251378865179075, 'feature_fraction': 0.5913121419392753, 'bagging_fraction': 0.7715501355676715, 'bagging_freq': 3}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 10:58:23,599] Trial 28 finished with value: 0.7225845784540109 and parameters: {'learning_rate': 0.047616011810605104, 'num_leaves': 49, 'max_depth': 6, 'min_child_samples': 130, 'subsample': 0.9564851310444118, 'colsample_bytree': 0.5123181779086612, 'lambda_l1': 0.00010489822359226727, 'lambda_l2': 0.0005495206145623622, 'max_bin': 443, 'n_estimators': 5567, 'scale_pos_weight': 1.8896587886228244, 'min_child_weight': 0.0018480520436661473, 'feature_fraction': 0.6577089998732792, 'bagging_fraction': 0.5111975102027893, 'bagging_freq': 5}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 10:58:51,256] Trial 29 finished with value: 0.7395733561164327 and parameters: {'learning_rate': 0.016151559357501483, 'num_leaves': 25, 'max_depth': 7, 'min_child_samples': 22, 'subsample': 0.9087530112976543, 'colsample_bytree': 0.6125164462350836, 'lambda_l1': 0.027144085158493966, 'lambda_l2': 0.0004296915538823678, 'max_bin': 360, 'n_estimators': 780, 'scale_pos_weight': 0.8006892646103189, 'min_child_weight': 0.0318960228283267, 'feature_fraction': 0.6588687993237444, 'bagging_fraction': 0.5115602343350313, 'bagging_freq': 5}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 10:59:42,838] Trial 30 finished with value: 0.7395324235470047 and parameters: {'learning_rate': 0.012264187148770181, 'num_leaves': 23, 'max_depth': 3, 'min_child_samples': 39, 'subsample': 0.9743471872988765, 'colsample_bytree': 0.9792349972160144, 'lambda_l1': 0.0017079682970036353, 'lambda_l2': 0.10361501419540765, 'max_bin': 486, 'n_estimators': 2071, 'scale_pos_weight': 1.013515126241556, 'min_child_weight': 0.07630867907345643, 'feature_fraction': 0.8699153763010493, 'bagging_fraction': 0.6731797788073467, 'bagging_freq': 3}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 11:02:15,333] Trial 31 finished with value: 0.7391313408197785 and parameters: {'learning_rate': 0.005012251147182272, 'num_leaves': 60, 'max_depth': 10, 'min_child_samples': 142, 'subsample': 0.77580533117583, 'colsample_bytree': 0.794504711621179, 'lambda_l1': 0.0008207536579463203, 'lambda_l2': 0.7025071059325388, 'max_bin': 369, 'n_estimators': 2560, 'scale_pos_weight': 0.8011397416324849, 'min_child_weight': 0.3587332189261461, 'feature_fraction': 0.851554030135764, 'bagging_fraction': 0.8243951017498098, 'bagging_freq': 5}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 11:02:39,509] Trial 32 finished with value: 0.7390353628411583 and parameters: {'learning_rate': 0.025141654409394323, 'num_leaves': 26, 'max_depth': 3, 'min_child_samples': 109, 'subsample': 0.6127660693780168, 'colsample_bytree': 0.7000140476796692, 'lambda_l1': 0.03646211564677214, 'lambda_l2': 1.2818247920989196, 'max_bin': 565, 'n_estimators': 766, 'scale_pos_weight': 1.359505179941848, 'min_child_weight': 0.020944242108526058, 'feature_fraction': 0.5466611972977665, 'bagging_fraction': 0.684310144689328, 'bagging_freq': 7}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 11:04:18,539] Trial 33 finished with value: 0.738793882376329 and parameters: {'learning_rate': 0.024770201537374407, 'num_leaves': 62, 'max_depth': 4, 'min_child_samples': 98, 'subsample': 0.5321208765627321, 'colsample_bytree': 0.8653226607515124, 'lambda_l1': 0.0019956001861067946, 'lambda_l2': 0.00026896147020164966, 'max_bin': 341, 'n_estimators': 2586, 'scale_pos_weight': 1.8251571592144205, 'min_child_weight': 0.004844410163112896, 'feature_fraction': 0.5301852990055433, 'bagging_fraction': 0.9802897861911202, 'bagging_freq': 6}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 11:05:13,366] Trial 34 finished with value: 0.7390653263746392 and parameters: {'learning_rate': 0.006525346932352508, 'num_leaves': 72, 'max_depth': 5, 'min_child_samples': 109, 'subsample': 0.9196611674854942, 'colsample_bytree': 0.5777173512671412, 'lambda_l1': 0.00012606395175895102, 'lambda_l2': 1.6615381715708872, 'max_bin': 201, 'n_estimators': 1180, 'scale_pos_weight': 1.490377745360507, 'min_child_weight': 0.041211792470109546, 'feature_fraction': 0.7636265822717172, 'bagging_fraction': 0.9331746234730321, 'bagging_freq': 4}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 11:06:25,906] Trial 35 finished with value: 0.7383383455527273 and parameters: {'learning_rate': 0.017844734095265914, 'num_leaves': 66, 'max_depth': 6, 'min_child_samples': 126, 'subsample': 0.7446545656351662, 'colsample_bytree': 0.7137437421752193, 'lambda_l1': 0.0009222826517733632, 'lambda_l2': 0.0006193385795398792, 'max_bin': 321, 'n_estimators': 1498, 'scale_pos_weight': 3.1619384042343137, 'min_child_weight': 0.001364536681951522, 'feature_fraction': 0.8893137565053364, 'bagging_fraction': 0.9702860209097595, 'bagging_freq': 5}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 11:09:08,229] Trial 36 finished with value: 0.7177587350401847 and parameters: {'learning_rate': 0.08946441056550691, 'num_leaves': 44, 'max_depth': 5, 'min_child_samples': 39, 'subsample': 0.9259791413850418, 'colsample_bytree': 0.9062615352048682, 'lambda_l1': 0.00024220397868224774, 'lambda_l2': 0.02793240152512607, 'max_bin': 290, 'n_estimators': 5146, 'scale_pos_weight': 2.54252589754969, 'min_child_weight': 4.343713847165133, 'feature_fraction': 0.6938339973639365, 'bagging_fraction': 0.5763406985103887, 'bagging_freq': 4}. Best is trial 27 with value: 0.7396130913924788.
[I 2025-02-26 11:10:19,020] Trial 37 finished with value: 0.7398059205596593 and parameters: {'learning_rate': 0.005817058550512746, 'num_leaves': 55, 'max_depth': 9, 'min_child_samples': 90, 'subsample': 0.7322451188571679, 'colsample_bytree': 0.5382926852387944, 'lambda_l1': 0.00380243981756742, 'lambda_l2': 0.029629484171191444, 'max_bin': 338, 'n_estimators': 1214, 'scale_pos_weight': 0.7743415462679393, 'min_child_weight': 0.04738493030921971, 'feature_fraction': 0.5893372806238872, 'bagging_fraction': 0.6654501994057781, 'bagging_freq': 6}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:12:50,398] Trial 38 finished with value: 0.7284110708519937 and parameters: {'learning_rate': 0.04641969292207587, 'num_leaves': 33, 'max_depth': 5, 'min_child_samples': 63, 'subsample': 0.9007815032035951, 'colsample_bytree': 0.6929840560739673, 'lambda_l1': 0.04223265220476459, 'lambda_l2': 0.6504504078397864, 'max_bin': 338, 'n_estimators': 4841, 'scale_pos_weight': 0.6592981794551737, 'min_child_weight': 0.005415307572705658, 'feature_fraction': 0.9374015427319199, 'bagging_fraction': 0.608409300405762, 'bagging_freq': 6}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:16:22,199] Trial 39 finished with value: 0.7372757250568593 and parameters: {'learning_rate': 0.005776121503172466, 'num_leaves': 45, 'max_depth': 8, 'min_child_samples': 77, 'subsample': 0.6263413478634487, 'colsample_bytree': 0.9180571978013401, 'lambda_l1': 0.7907861302176193, 'lambda_l2': 0.019952437516188838, 'max_bin': 113, 'n_estimators': 5152, 'scale_pos_weight': 2.5926780577528112, 'min_child_weight': 0.04429912905115603, 'feature_fraction': 0.8751288829402358, 'bagging_fraction': 0.5586781435408982, 'bagging_freq': 1}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:18:12,337] Trial 40 finished with value: 0.7393731759972345 and parameters: {'learning_rate': 0.022766497935089898, 'num_leaves': 44, 'max_depth': 3, 'min_child_samples': 97, 'subsample': 0.8039302376621014, 'colsample_bytree': 0.6675537989746242, 'lambda_l1': 0.0009951234936272002, 'lambda_l2': 0.0009402731190827328, 'max_bin': 148, 'n_estimators': 2830, 'scale_pos_weight': 0.6579031419638388, 'min_child_weight': 0.055940341590128694, 'feature_fraction': 0.5645755091430935, 'bagging_fraction': 0.995372154237132, 'bagging_freq': 2}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:20:45,877] Trial 41 finished with value: 0.7184781095537591 and parameters: {'learning_rate': 0.060692481945029, 'num_leaves': 61, 'max_depth': 10, 'min_child_samples': 34, 'subsample': 0.5679237612103543, 'colsample_bytree': 0.9793806143055515, 'lambda_l1': 0.7168110939890452, 'lambda_l2': 0.5509562455103153, 'max_bin': 132, 'n_estimators': 2897, 'scale_pos_weight': 0.5402649946292223, 'min_child_weight': 3.009239139743045, 'feature_fraction': 0.6177277892731838, 'bagging_fraction': 0.5754188574142611, 'bagging_freq': 6}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:22:09,928] Trial 42 finished with value: 0.7367840173809828 and parameters: {'learning_rate': 0.026206402704282334, 'num_leaves': 78, 'max_depth': 6, 'min_child_samples': 137, 'subsample': 0.5666128683478466, 'colsample_bytree': 0.8471208662001887, 'lambda_l1': 0.1006143047271666, 'lambda_l2': 0.031748232755823474, 'max_bin': 337, 'n_estimators': 1936, 'scale_pos_weight': 1.2388683183164835, 'min_child_weight': 2.7711325607312953, 'feature_fraction': 0.8007266459761538, 'bagging_fraction': 0.8371592965124007, 'bagging_freq': 4}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:23:54,890] Trial 43 finished with value: 0.7290061249202446 and parameters: {'learning_rate': 0.04388874967213125, 'num_leaves': 21, 'max_depth': 10, 'min_child_samples': 45, 'subsample': 0.5151321374139998, 'colsample_bytree': 0.7612748187925413, 'lambda_l1': 0.013896086142221183, 'lambda_l2': 0.074417286707534, 'max_bin': 305, 'n_estimators': 3659, 'scale_pos_weight': 3.1070474667537913, 'min_child_weight': 2.570186158702525, 'feature_fraction': 0.781608918839886, 'bagging_fraction': 0.5734057760642943, 'bagging_freq': 7}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:25:03,806] Trial 44 finished with value: 0.7392992590948635 and parameters: {'learning_rate': 0.0057810761374206075, 'num_leaves': 60, 'max_depth': 3, 'min_child_samples': 69, 'subsample': 0.7957306050662474, 'colsample_bytree': 0.971866968637497, 'lambda_l1': 0.15969624771204743, 'lambda_l2': 0.005394602558895395, 'max_bin': 404, 'n_estimators': 3402, 'scale_pos_weight': 4.437613624802536, 'min_child_weight': 0.03789154843292917, 'feature_fraction': 0.8844532709971817, 'bagging_fraction': 0.5622721020458482, 'bagging_freq': 7}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:26:05,960] Trial 45 finished with value: 0.7363409498466758 and parameters: {'learning_rate': 0.025255462084940117, 'num_leaves': 55, 'max_depth': 6, 'min_child_samples': 58, 'subsample': 0.5801402152213541, 'colsample_bytree': 0.8434771131629768, 'lambda_l1': 0.0002854114550924589, 'lambda_l2': 0.06888603264081371, 'max_bin': 559, 'n_estimators': 1785, 'scale_pos_weight': 2.947021397470179, 'min_child_weight': 1.678699180974346, 'feature_fraction': 0.6982924863628006, 'bagging_fraction': 0.6124478230226023, 'bagging_freq': 1}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:27:59,643] Trial 46 finished with value: 0.7340961187843266 and parameters: {'learning_rate': 0.039484352468716996, 'num_leaves': 69, 'max_depth': 6, 'min_child_samples': 89, 'subsample': 0.8454671773330276, 'colsample_bytree': 0.9660486752270454, 'lambda_l1': 0.0013590789661925967, 'lambda_l2': 0.05275600655967893, 'max_bin': 271, 'n_estimators': 2514, 'scale_pos_weight': 0.5091404032363792, 'min_child_weight': 0.10637552904921574, 'feature_fraction': 0.5875883467920069, 'bagging_fraction': 0.9543187896643602, 'bagging_freq': 5}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:31:00,004] Trial 47 finished with value: 0.7271493430819481 and parameters: {'learning_rate': 0.02963134019579447, 'num_leaves': 59, 'max_depth': 10, 'min_child_samples': 47, 'subsample': 0.8502993869156741, 'colsample_bytree': 0.8909225907322974, 'lambda_l1': 0.000268090907188252, 'lambda_l2': 0.13019197323942416, 'max_bin': 483, 'n_estimators': 3645, 'scale_pos_weight': 1.136189430447951, 'min_child_weight': 0.0011163178344784058, 'feature_fraction': 0.6946447571981667, 'bagging_fraction': 0.9107536529622516, 'bagging_freq': 4}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:34:04,827] Trial 48 finished with value: 0.7290287623372237 and parameters: {'learning_rate': 0.02456914363016111, 'num_leaves': 54, 'max_depth': 7, 'min_child_samples': 150, 'subsample': 0.9996815233699654, 'colsample_bytree': 0.5771836710443985, 'lambda_l1': 0.34777325994637476, 'lambda_l2': 0.0019691853952277577, 'max_bin': 276, 'n_estimators': 4725, 'scale_pos_weight': 0.6283927035410773, 'min_child_weight': 0.12447129842078695, 'feature_fraction': 0.7714088664707248, 'bagging_fraction': 0.583268396090052, 'bagging_freq': 1}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 11:37:09,409] Trial 49 finished with value: 0.7386235952840943 and parameters: {'learning_rate': 0.011800867063668176, 'num_leaves': 36, 'max_depth': 4, 'min_child_samples': 102, 'subsample': 0.6801240292930595, 'colsample_bytree': 0.839647003384659, 'lambda_l1': 0.00019912783752390532, 'lambda_l2': 0.0005618468994541301, 'max_bin': 544, 'n_estimators': 4911, 'scale_pos_weight': 3.1395784405077665, 'min_child_weight': 0.10822426179299321, 'feature_fraction': 0.9408948492742599, 'bagging_fraction': 0.8586813870017456, 'bagging_freq': 2}. Best is trial 37 with value: 0.7398059205596593.

{'learning_rate': 0.005817058550512746, 'num_leaves': 55, 'max_depth': 9, 'min_child_samples': 90, 'subsample': 0.7322451188571679, 'colsample_bytree': 0.5382926852387944, 'lambda_l1': 0.00380243981756742, 'lambda_l2': 0.029629484171191444, 'max_bin': 338, 'n_estimators': 1214, 'scale_pos_weight': 0.7743415462679393, 'min_child_weight': 0.04738493030921971, 'feature_fraction': 0.5893372806238872, 'bagging_fraction': 0.6654501994057781, 'bagging_freq': 6} 0.7398059205596593

In [26]:
study.sampler = optuna.samplers.TPESampler(seed=RANDOM_STATE)  # TPESampler 시드 고정
print(study.sampler)

study.optimize(lambda trial: objective(trial, top5_df['ratio'][0], top5_df['model'][0]), n_trials=100)

params, auc = study.best_params, study.best_value
print(params, auc)
top5_df.loc[0, ['param', 'tuned_auc']] =  params, auc

# Study 저장
with open("./data/optuna_study_100.pkl", "wb") as f:
    pickle.dump(study, f)

# Study 불러오기
with open("./data/optuna_study_100.pkl", "rb") as f:
    study = pickle.load(f)

TPESampler

[I 2025-02-26 13:33:20,116] Trial 50 finished with value: 0.7390716789215895 and parameters: {'learning_rate': 0.009400077337916118, 'num_leaves': 28, 'max_depth': 9, 'min_child_samples': 84, 'subsample': 0.8171180821269252, 'colsample_bytree': 0.5508358063588705, 'lambda_l1': 0.004632619736363163, 'lambda_l2': 0.32100657383455367, 'max_bin': 158, 'n_estimators': 540, 'scale_pos_weight': 2.1852904190483646, 'min_child_weight': 0.0031187523232613194, 'feature_fraction': 0.6024817321250162, 'bagging_fraction': 0.5049360999237884, 'bagging_freq': 6}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 13:34:48,194] Trial 51 finished with value: 0.7396838604068299 and parameters: {'learning_rate': 0.008522646668550087, 'num_leaves': 24, 'max_depth': 9, 'min_child_samples': 24, 'subsample': 0.8781669377132313, 'colsample_bytree': 0.5505961619084916, 'lambda_l1': 0.004322676596353319, 'lambda_l2': 0.009903555783612312, 'max_bin': 511, 'n_estimators': 2055, 'scale_pos_weight': 0.9537344099740372, 'min_child_weight': 0.008512377503399556, 'feature_fraction': 0.5747990079437907, 'bagging_fraction': 0.5370650177648306, 'bagging_freq': 3}. Best is trial 37 with value: 0.7398059205596593.
[I 2025-02-26 13:35:45,794] Trial 52 finished with value: 0.7398650815864358 and parameters: {'learning_rate': 0.00935953579791642, 'num_leaves': 26, 'max_depth': 9, 'min_child_samples': 119, 'subsample': 0.8857714185731538, 'colsample_bytree': 0.5532610550481468, 'lambda_l1': 0.0050306487157325205, 'lambda_l2': 0.010376952485061194, 'max_bin': 502, 'n_estimators': 1235, 'scale_pos_weight': 0.9250427866924747, 'min_child_weight': 0.009095739137064556, 'feature_fraction': 0.5068066415394435, 'bagging_fraction': 0.5317046073963605, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:36:32,486] Trial 53 finished with value: 0.7397538633685312 and parameters: {'learning_rate': 0.008899679348040005, 'num_leaves': 24, 'max_depth': 8, 'min_child_samples': 125, 'subsample': 0.8762003218754852, 'colsample_bytree': 0.5064883303561448, 'lambda_l1': 0.0038504036137837374, 'lambda_l2': 0.014572620072774937, 'max_bin': 600, 'n_estimators': 1035, 'scale_pos_weight': 0.9378044933319027, 'min_child_weight': 0.011937956356620682, 'feature_fraction': 0.5051415455354793, 'bagging_fraction': 0.5310457621221203, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:37:22,950] Trial 54 finished with value: 0.7398138169466091 and parameters: {'learning_rate': 0.008559469189471225, 'num_leaves': 28, 'max_depth': 9, 'min_child_samples': 122, 'subsample': 0.8742433792520377, 'colsample_bytree': 0.5031165389137295, 'lambda_l1': 0.00429383407142569, 'lambda_l2': 0.010343602468091545, 'max_bin': 594, 'n_estimators': 1065, 'scale_pos_weight': 0.9280905181268577, 'min_child_weight': 0.01070072647056994, 'feature_fraction': 0.527186229778128, 'bagging_fraction': 0.5369463642208551, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:38:16,864] Trial 55 finished with value: 0.7397855690343509 and parameters: {'learning_rate': 0.008211017706224172, 'num_leaves': 27, 'max_depth': 9, 'min_child_samples': 120, 'subsample': 0.8744402782732236, 'colsample_bytree': 0.5096634060870039, 'lambda_l1': 0.003345962078384255, 'lambda_l2': 0.009955784427973968, 'max_bin': 593, 'n_estimators': 1104, 'scale_pos_weight': 0.9099758121852446, 'min_child_weight': 0.009385562410646676, 'feature_fraction': 0.50162594408391, 'bagging_fraction': 0.5395646741407054, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:39:10,558] Trial 56 finished with value: 0.7398141262740735 and parameters: {'learning_rate': 0.008787379797646126, 'num_leaves': 27, 'max_depth': 9, 'min_child_samples': 119, 'subsample': 0.8809435285319901, 'colsample_bytree': 0.5016298567746006, 'lambda_l1': 0.0036138776453409904, 'lambda_l2': 0.009566149333474085, 'max_bin': 599, 'n_estimators': 1067, 'scale_pos_weight': 1.096719631582407, 'min_child_weight': 0.008711045042387067, 'feature_fraction': 0.5039756603415521, 'bagging_fraction': 0.5383093669010497, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:40:04,158] Trial 57 finished with value: 0.7398294956722291 and parameters: {'learning_rate': 0.01022243968214509, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 119, 'subsample': 0.8710928869042781, 'colsample_bytree': 0.5015696683005701, 'lambda_l1': 0.00723171483855125, 'lambda_l2': 0.009995720957920454, 'max_bin': 595, 'n_estimators': 1098, 'scale_pos_weight': 0.9076796323585533, 'min_child_weight': 0.009155321224879375, 'feature_fraction': 0.5004645754094904, 'bagging_fraction': 0.5311954278454009, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:40:54,369] Trial 58 finished with value: 0.7397691341750563 and parameters: {'learning_rate': 0.0075266986858263454, 'num_leaves': 31, 'max_depth': 9, 'min_child_samples': 120, 'subsample': 0.8297785208342021, 'colsample_bytree': 0.5341858362038442, 'lambda_l1': 0.0076062461459035086, 'lambda_l2': 0.009132444474089077, 'max_bin': 593, 'n_estimators': 1052, 'scale_pos_weight': 1.1110201840167162, 'min_child_weight': 0.00788539954341759, 'feature_fraction': 0.5095989364233909, 'bagging_fraction': 0.5424151913313017, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:41:54,803] Trial 59 finished with value: 0.7398116313426213 and parameters: {'learning_rate': 0.01079330129200187, 'num_leaves': 27, 'max_depth': 8, 'min_child_samples': 118, 'subsample': 0.8624804290985477, 'colsample_bytree': 0.5011731138317964, 'lambda_l1': 0.0004530330859342783, 'lambda_l2': 0.0037256176687722703, 'max_bin': 581, 'n_estimators': 1424, 'scale_pos_weight': 0.8664818706141793, 'min_child_weight': 0.002855932575361509, 'feature_fraction': 0.5278759172352363, 'bagging_fraction': 0.5507855365067359, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:43:01,069] Trial 60 finished with value: 0.7398079749462552 and parameters: {'learning_rate': 0.010245805352891412, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 119, 'subsample': 0.8593985289555407, 'colsample_bytree': 0.5640249744165137, 'lambda_l1': 0.0005356676961562217, 'lambda_l2': 0.003917606074556924, 'max_bin': 519, 'n_estimators': 1382, 'scale_pos_weight': 0.7100898776595669, 'min_child_weight': 0.002706568596647673, 'feature_fraction': 0.5285245472989307, 'bagging_fraction': 0.6264151749055202, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:44:05,045] Trial 61 finished with value: 0.739445254570612 and parameters: {'learning_rate': 0.013688977617418108, 'num_leaves': 34, 'max_depth': 8, 'min_child_samples': 122, 'subsample': 0.8904171865383035, 'colsample_bytree': 0.5656520443284351, 'lambda_l1': 0.00044143774887560756, 'lambda_l2': 0.0031015637311678696, 'max_bin': 514, 'n_estimators': 1292, 'scale_pos_weight': 0.7574301450009936, 'min_child_weight': 0.013204577245691915, 'feature_fraction': 0.5283642409760794, 'bagging_fraction': 0.6310816718586562, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:44:33,825] Trial 62 finished with value: 0.7390780901671894 and parameters: {'learning_rate': 0.010382825762088535, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 132, 'subsample': 0.8541657021065067, 'colsample_bytree': 0.500454845919862, 'lambda_l1': 0.0026387702197413344, 'lambda_l2': 0.004343380954593515, 'max_bin': 575, 'n_estimators': 542, 'scale_pos_weight': 0.8609069217135701, 'min_child_weight': 0.002920496098873354, 'feature_fraction': 0.5278510872858762, 'bagging_fraction': 0.556700945561565, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:45:34,403] Trial 63 finished with value: 0.7398417276914669 and parameters: {'learning_rate': 0.010423132647188287, 'num_leaves': 30, 'max_depth': 9, 'min_child_samples': 116, 'subsample': 0.9436072248161275, 'colsample_bytree': 0.5312974171004763, 'lambda_l1': 0.0004907126120329599, 'lambda_l2': 0.003383326327093039, 'max_bin': 525, 'n_estimators': 1497, 'scale_pos_weight': 1.0430301121200989, 'min_child_weight': 0.002552459740015618, 'feature_fraction': 0.549014587580176, 'bagging_fraction': 0.5192759776554623, 'bagging_freq': 4}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:46:35,655] Trial 64 finished with value: 0.7398041880404718 and parameters: {'learning_rate': 0.010533188135547506, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 116, 'subsample': 0.9451909466301099, 'colsample_bytree': 0.5232947090313933, 'lambda_l1': 0.0006193606062725355, 'lambda_l2': 0.003061977252884879, 'max_bin': 517, 'n_estimators': 1472, 'scale_pos_weight': 1.04713766423863, 'min_child_weight': 0.0032632024399315298, 'feature_fraction': 0.5564633794789929, 'bagging_fraction': 0.5233861651484231, 'bagging_freq': 4}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:47:19,214] Trial 65 finished with value: 0.7397113122562997 and parameters: {'learning_rate': 0.013992609370875568, 'num_leaves': 40, 'max_depth': 9, 'min_child_samples': 117, 'subsample': 0.9410288589141234, 'colsample_bytree': 0.6015923888845598, 'lambda_l1': 0.0004720323371511962, 'lambda_l2': 0.004363456396545423, 'max_bin': 582, 'n_estimators': 863, 'scale_pos_weight': 0.8800841257845269, 'min_child_weight': 0.00236876342027843, 'feature_fraction': 0.5404306567958012, 'bagging_fraction': 0.522172889746349, 'bagging_freq': 3}. Best is trial 52 with value: 0.7398650815864358.
[I 2025-02-26 13:48:32,353] Trial 66 finished with value: 0.739931364794222 and parameters: {'learning_rate': 0.00715876129129083, 'num_leaves': 34, 'max_depth': 8, 'min_child_samples': 141, 'subsample': 0.8280629698052999, 'colsample_bytree': 0.5611193872620674, 'lambda_l1': 0.00793505837431822, 'lambda_l2': 0.007532449852224381, 'max_bin': 544, 'n_estimators': 1477, 'scale_pos_weight': 0.7193598122622171, 'min_child_weight': 0.005986447061673284, 'feature_fraction': 0.51739395601726, 'bagging_fraction': 0.5497429374919354, 'bagging_freq': 3}. Best is trial 66 with value: 0.739931364794222.
[I 2025-02-26 13:50:21,208] Trial 67 finished with value: 0.7395654708146067 and parameters: {'learning_rate': 0.006862199363997027, 'num_leaves': 40, 'max_depth': 9, 'min_child_samples': 143, 'subsample': 0.8252697513621041, 'colsample_bytree': 0.5464597931328932, 'lambda_l1': 0.006209154896068675, 'lambda_l2': 0.007154148978938945, 'max_bin': 539, 'n_estimators': 2224, 'scale_pos_weight': 1.2296857970695645, 'min_child_weight': 0.006555498157162398, 'feature_fraction': 0.5179363975731573, 'bagging_fraction': 0.5001492610916961, 'bagging_freq': 4}. Best is trial 66 with value: 0.739931364794222.
[I 2025-02-26 13:51:43,007] Trial 68 finished with value: 0.7399178364820364 and parameters: {'learning_rate': 0.007484583218501231, 'num_leaves': 34, 'max_depth': 8, 'min_child_samples': 129, 'subsample': 0.8883897937306731, 'colsample_bytree': 0.5221124883355662, 'lambda_l1': 0.011229457487037383, 'lambda_l2': 0.020558589487951417, 'max_bin': 539, 'n_estimators': 1621, 'scale_pos_weight': 1.0594334252192301, 'min_child_weight': 0.011360978715629638, 'feature_fraction': 0.547942653481727, 'bagging_fraction': 0.5539729173340256, 'bagging_freq': 2}. Best is trial 66 with value: 0.739931364794222.
[I 2025-02-26 13:52:36,539] Trial 69 finished with value: 0.7398486024027424 and parameters: {'learning_rate': 0.0074392311904597375, 'num_leaves': 35, 'max_depth': 9, 'min_child_samples': 126, 'subsample': 0.8964661511958807, 'colsample_bytree': 0.632803816165622, 'lambda_l1': 0.007208693798044868, 'lambda_l2': 0.021958465602887455, 'max_bin': 536, 'n_estimators': 957, 'scale_pos_weight': 1.0717884707211685, 'min_child_weight': 0.012236450971183442, 'feature_fraction': 0.569562267496756, 'bagging_fraction': 0.5915206216937804, 'bagging_freq': 2}. Best is trial 66 with value: 0.739931364794222.
[I 2025-02-26 13:54:02,301] Trial 70 finished with value: 0.7398612643466804 and parameters: {'learning_rate': 0.0072402206002751554, 'num_leaves': 35, 'max_depth': 7, 'min_child_samples': 128, 'subsample': 0.8921407760662584, 'colsample_bytree': 0.6282469781549781, 'lambda_l1': 0.009957262134480565, 'lambda_l2': 0.020385975080929094, 'max_bin': 471, 'n_estimators': 1642, 'scale_pos_weight': 1.039134486895807, 'min_child_weight': 0.006816305329269832, 'feature_fraction': 0.5697007642531117, 'bagging_fraction': 0.5957840076010378, 'bagging_freq': 2}. Best is trial 66 with value: 0.739931364794222.
[I 2025-02-26 13:55:24,179] Trial 71 finished with value: 0.739860893295402 and parameters: {'learning_rate': 0.007656271000082335, 'num_leaves': 34, 'max_depth': 7, 'min_child_samples': 128, 'subsample': 0.8926517341566861, 'colsample_bytree': 0.6427619757682339, 'lambda_l1': 0.011188033444661098, 'lambda_l2': 0.018971113074609258, 'max_bin': 488, 'n_estimators': 1654, 'scale_pos_weight': 1.0285838648324723, 'min_child_weight': 0.015054241039034409, 'feature_fraction': 0.5732282025861539, 'bagging_fraction': 0.5921102261134983, 'bagging_freq': 2}. Best is trial 66 with value: 0.739931364794222.
[I 2025-02-26 13:56:53,081] Trial 72 finished with value: 0.7398111692063297 and parameters: {'learning_rate': 0.007171811786543342, 'num_leaves': 35, 'max_depth': 7, 'min_child_samples': 129, 'subsample': 0.90173980953555, 'colsample_bytree': 0.6404031070302305, 'lambda_l1': 0.011648087707250782, 'lambda_l2': 0.018311411773196788, 'max_bin': 475, 'n_estimators': 1841, 'scale_pos_weight': 1.0294361617438201, 'min_child_weight': 0.014395710302382644, 'feature_fraction': 0.5774646667560328, 'bagging_fraction': 0.5929191482029466, 'bagging_freq': 2}. Best is trial 66 with value: 0.739931364794222.
[I 2025-02-26 13:58:22,122] Trial 73 finished with value: 0.7399534783757404 and parameters: {'learning_rate': 0.006364895299663814, 'num_leaves': 39, 'max_depth': 7, 'min_child_samples': 141, 'subsample': 0.9346778761950136, 'colsample_bytree': 0.6385824206515566, 'lambda_l1': 0.01577581889916208, 'lambda_l2': 0.020663831573689794, 'max_bin': 495, 'n_estimators': 1650, 'scale_pos_weight': 1.208432490137452, 'min_child_weight': 0.0267606305563961, 'feature_fraction': 0.552458193333866, 'bagging_fraction': 0.611779633276765, 'bagging_freq': 2}. Best is trial 73 with value: 0.7399534783757404.
[I 2025-02-26 13:59:40,761] Trial 74 finished with value: 0.7398150324367566 and parameters: {'learning_rate': 0.0077049093988692755, 'num_leaves': 39, 'max_depth': 7, 'min_child_samples': 142, 'subsample': 0.9337985098830119, 'colsample_bytree': 0.6438033250255014, 'lambda_l1': 0.020330120832443916, 'lambda_l2': 0.023172588492561725, 'max_bin': 532, 'n_estimators': 1659, 'scale_pos_weight': 1.572657435523595, 'min_child_weight': 0.006467345836201036, 'feature_fraction': 0.6189392228655781, 'bagging_fraction': 0.6073158162729024, 'bagging_freq': 2}. Best is trial 73 with value: 0.7399534783757404.
[I 2025-02-26 14:01:02,354] Trial 75 finished with value: 0.7399387466041422 and parameters: {'learning_rate': 0.006467454875822133, 'num_leaves': 38, 'max_depth': 7, 'min_child_samples': 146, 'subsample': 0.9880365897326107, 'colsample_bytree': 0.632597048457714, 'lambda_l1': 0.009855197309213658, 'lambda_l2': 0.0070339690261793965, 'max_bin': 459, 'n_estimators': 1589, 'scale_pos_weight': 1.2972549331383445, 'min_child_weight': 0.026716801963853547, 'feature_fraction': 0.5500997013395802, 'bagging_fraction': 0.5915275167208287, 'bagging_freq': 2}. Best is trial 73 with value: 0.7399534783757404.
[I 2025-02-26 14:03:06,767] Trial 76 finished with value: 0.739793079908289 and parameters: {'learning_rate': 0.0063169362130471906, 'num_leaves': 38, 'max_depth': 7, 'min_child_samples': 139, 'subsample': 0.9580021129295702, 'colsample_bytree': 0.6257625418873576, 'lambda_l1': 0.05189271347734246, 'lambda_l2': 0.014203821729825655, 'max_bin': 492, 'n_estimators': 2305, 'scale_pos_weight': 1.2073163399979747, 'min_child_weight': 0.029974007399751586, 'feature_fraction': 0.5646110818446133, 'bagging_fraction': 0.656854607744876, 'bagging_freq': 2}. Best is trial 73 with value: 0.7399534783757404.
[I 2025-02-26 14:04:42,569] Trial 77 finished with value: 0.7399021130565572 and parameters: {'learning_rate': 0.006376435785328791, 'num_leaves': 46, 'max_depth': 7, 'min_child_samples': 144, 'subsample': 0.9724478182001833, 'colsample_bytree': 0.6675083811587804, 'lambda_l1': 0.011536945990065835, 'lambda_l2': 0.0230263178866037, 'max_bin': 467, 'n_estimators': 1647, 'scale_pos_weight': 1.3016885548179955, 'min_child_weight': 0.025008333514799024, 'feature_fraction': 0.5434530225263671, 'bagging_fraction': 0.6436831122690513, 'bagging_freq': 2}. Best is trial 73 with value: 0.7399534783757404.
[I 2025-02-26 14:06:08,319] Trial 78 finished with value: 0.7396655602853487 and parameters: {'learning_rate': 0.00652801158485512, 'num_leaves': 48, 'max_depth': 7, 'min_child_samples': 146, 'subsample': 0.9864311740712125, 'colsample_bytree': 0.6733139711577522, 'lambda_l1': 0.009824688420807665, 'lambda_l2': 0.007080014030121226, 'max_bin': 464, 'n_estimators': 1973, 'scale_pos_weight': 1.4224236251555282, 'min_child_weight': 0.029296170095303643, 'feature_fraction': 0.6029929100171948, 'bagging_fraction': 0.6444132911899525, 'bagging_freq': 1}. Best is trial 73 with value: 0.7399534783757404.
[I 2025-02-26 14:07:34,934] Trial 79 finished with value: 0.7399634058912147 and parameters: {'learning_rate': 0.005508277931286193, 'num_leaves': 41, 'max_depth': 7, 'min_child_samples': 134, 'subsample': 0.9702439925373975, 'colsample_bytree': 0.5981718723138733, 'lambda_l1': 0.016240028716597917, 'lambda_l2': 0.05110057380337157, 'max_bin': 433, 'n_estimators': 1626, 'scale_pos_weight': 1.7019186904587489, 'min_child_weight': 0.017264670052028027, 'feature_fraction': 0.5451974100766874, 'bagging_fraction': 0.6234940856004552, 'bagging_freq': 2}. Best is trial 79 with value: 0.7399634058912147.
[I 2025-02-26 14:09:43,541] Trial 80 finished with value: 0.7398087705182544 and parameters: {'learning_rate': 0.005455595102060486, 'num_leaves': 46, 'max_depth': 7, 'min_child_samples': 146, 'subsample': 0.9749659788970986, 'colsample_bytree': 0.6026302965959971, 'lambda_l1': 0.020133994110399803, 'lambda_l2': 0.05619363264868635, 'max_bin': 430, 'n_estimators': 2240, 'scale_pos_weight': 1.7310922324522413, 'min_child_weight': 0.022939642239761925, 'feature_fraction': 0.5407907669519516, 'bagging_fraction': 0.7035914289879455, 'bagging_freq': 2}. Best is trial 79 with value: 0.7399634058912147.
[I 2025-02-26 14:11:08,163] Trial 81 finished with value: 0.739958521104378 and parameters: {'learning_rate': 0.005993150681031572, 'num_leaves': 42, 'max_depth': 7, 'min_child_samples': 135, 'subsample': 0.9631117662938071, 'colsample_bytree': 0.6563253997397683, 'lambda_l1': 0.015130156767871456, 'lambda_l2': 0.04158010131248849, 'max_bin': 501, 'n_estimators': 1613, 'scale_pos_weight': 1.307263101838483, 'min_child_weight': 0.01781532462639362, 'feature_fraction': 0.5571027462747908, 'bagging_fraction': 0.6186051196474475, 'bagging_freq': 2}. Best is trial 79 with value: 0.7399634058912147.
[I 2025-02-26 14:12:38,498] Trial 82 finished with value: 0.7398358164546313 and parameters: {'learning_rate': 0.006138703134517321, 'num_leaves': 42, 'max_depth': 7, 'min_child_samples': 133, 'subsample': 0.9560458334542566, 'colsample_bytree': 0.6564233152131883, 'lambda_l1': 0.013906147610041122, 'lambda_l2': 0.04074977973269979, 'max_bin': 498, 'n_estimators': 1857, 'scale_pos_weight': 1.2843877090336648, 'min_child_weight': 0.016943185437122567, 'feature_fraction': 0.5578043286293085, 'bagging_fraction': 0.6155980387977387, 'bagging_freq': 1}. Best is trial 79 with value: 0.7399634058912147.

{'learning_rate': 0.005034983060822145, 'num_leaves': 36, 'max_depth': 7, 'min_child_samples': 147, 'subsample': 0.9109603413137686, 'colsample_bytree': 0.7468857214614529, 'lambda_l1': 0.0017197720809456513, 'lambda_l2': 0.2756008731148777, 'max_bin': 494, 'n_estimators': 1691, 'scale_pos_weight': 1.7724248071595592, 'min_child_weight': 1.0892590244720923, 'feature_fraction': 0.8154619713418669, 'bagging_fraction': 0.5148378269219118, 'bagging_freq': 2} 0.7400296340017085

In [27]:
study.optimize(lambda trial: objective(trial, top5_df['ratio'][0], top5_df['model'][0]), n_trials=100)

params, auc = study.best_params, study.best_value
print(params, auc)
top5_df.loc[0, ['param', 'tuned_auc']] =  params, auc


# Study 저장
with open("./data/optuna_study_200.pkl", "wb") as f:
    pickle.dump(study, f)

# Study 불러오기
with open("./data/optuna_study_200.pkl", "rb") as f:
    study = pickle.load(f)

[I 2025-02-26 16:38:25,903] Trial 150 finished with value: 0.7399874065119407 and parameters: {'learning_rate': 0.005421446931613538, 'num_leaves': 33, 'max_depth': 8, 'min_child_samples': 124, 'subsample': 0.9556357111815003, 'colsample_bytree': 0.8143559646751638, 'lambda_l1': 0.0011049977580733963, 'lambda_l2': 0.40003315903423925, 'max_bin': 520, 'n_estimators': 1610, 'scale_pos_weight': 3.272190364686397, 'min_child_weight': 2.1952330639339515, 'feature_fraction': 0.7854122208997758, 'bagging_fraction': 0.5269999340339792, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:39:44,075] Trial 151 finished with value: 0.7399573081908659 and parameters: {'learning_rate': 0.005445654428901667, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 124, 'subsample': 0.9562710276169445, 'colsample_bytree': 0.8123793376093087, 'lambda_l1': 0.001983638096728173, 'lambda_l2': 0.25990254223760195, 'max_bin': 521, 'n_estimators': 1732, 'scale_pos_weight': 3.431972541905964, 'min_child_weight': 2.2068353245078556, 'feature_fraction': 0.8262321516792647, 'bagging_fraction': 0.5263265118653936, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:40:54,401] Trial 152 finished with value: 0.7399730933740776 and parameters: {'learning_rate': 0.006377773073133088, 'num_leaves': 33, 'max_depth': 8, 'min_child_samples': 139, 'subsample': 0.9665787498079272, 'colsample_bytree': 0.8255562611258157, 'lambda_l1': 0.0010336566529294833, 'lambda_l2': 0.41261431418792144, 'max_bin': 504, 'n_estimators': 1579, 'scale_pos_weight': 3.756314066307377, 'min_child_weight': 1.8147371215398922, 'feature_fraction': 0.7850646209886515, 'bagging_fraction': 0.5107698577406494, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:42:17,363] Trial 153 finished with value: 0.7398304892579848 and parameters: {'learning_rate': 0.0065126548874782685, 'num_leaves': 33, 'max_depth': 8, 'min_child_samples': 139, 'subsample': 0.971741549005929, 'colsample_bytree': 0.8298878796980226, 'lambda_l1': 0.0010664586740274738, 'lambda_l2': 0.3603459606771927, 'max_bin': 514, 'n_estimators': 1887, 'scale_pos_weight': 3.805845485973066, 'min_child_weight': 1.9133770684743407, 'feature_fraction': 0.78533579375613, 'bagging_fraction': 0.5113823382086762, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:43:24,760] Trial 154 finished with value: 0.739933245441519 and parameters: {'learning_rate': 0.005003183686534187, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 141, 'subsample': 0.9433900757637634, 'colsample_bytree': 0.8624850046034575, 'lambda_l1': 0.0003718918446068164, 'lambda_l2': 0.42760663740181254, 'max_bin': 489, 'n_estimators': 1550, 'scale_pos_weight': 3.2927187938483633, 'min_child_weight': 1.3852899439546265, 'feature_fraction': 0.7714378619153924, 'bagging_fraction': 0.5417493725841341, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:44:38,780] Trial 155 finished with value: 0.7400135721171289 and parameters: {'learning_rate': 0.005617027002075516, 'num_leaves': 34, 'max_depth': 8, 'min_child_samples': 143, 'subsample': 0.9888557795600128, 'colsample_bytree': 0.7700357949373795, 'lambda_l1': 0.0014311533116325155, 'lambda_l2': 1.3464983496778689, 'max_bin': 548, 'n_estimators': 1706, 'scale_pos_weight': 2.9551386651285734, 'min_child_weight': 2.6575994499432496, 'feature_fraction': 0.8429777656250924, 'bagging_fraction': 0.5196016216265005, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:45:59,858] Trial 156 finished with value: 0.7400241658610011 and parameters: {'learning_rate': 0.005357536323738182, 'num_leaves': 34, 'max_depth': 8, 'min_child_samples': 138, 'subsample': 0.987972931065861, 'colsample_bytree': 0.8052230726768389, 'lambda_l1': 0.0012501223089613368, 'lambda_l2': 1.845232340564576, 'max_bin': 556, 'n_estimators': 1789, 'scale_pos_weight': 2.90104170298054, 'min_child_weight': 2.7539403284961748, 'feature_fraction': 0.8464083530271973, 'bagging_fraction': 0.5197510184819905, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:47:17,505] Trial 157 finished with value: 0.7400067396678295 and parameters: {'learning_rate': 0.00530515046984052, 'num_leaves': 29, 'max_depth': 8, 'min_child_samples': 139, 'subsample': 0.9901344766010581, 'colsample_bytree': 0.8053365241438362, 'lambda_l1': 0.0012349057864339235, 'lambda_l2': 1.743362652539835, 'max_bin': 565, 'n_estimators': 1787, 'scale_pos_weight': 4.082226025580481, 'min_child_weight': 2.5393842393329504, 'feature_fraction': 0.8041826706354546, 'bagging_fraction': 0.5221088046353252, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:48:33,328] Trial 158 finished with value: 0.7400003233842704 and parameters: {'learning_rate': 0.005374878758939541, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 140, 'subsample': 0.9999150923027046, 'colsample_bytree': 0.8053348683365774, 'lambda_l1': 0.001185394145098118, 'lambda_l2': 1.7163154162463021, 'max_bin': 561, 'n_estimators': 1801, 'scale_pos_weight': 3.667974557968394, 'min_child_weight': 2.7237360841300564, 'feature_fraction': 0.84396919671971, 'bagging_fraction': 0.5193340487229632, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:49:59,611] Trial 159 finished with value: 0.7399799367196639 and parameters: {'learning_rate': 0.005391982086491511, 'num_leaves': 27, 'max_depth': 8, 'min_child_samples': 137, 'subsample': 0.9989108681730102, 'colsample_bytree': 0.8230533676317986, 'lambda_l1': 0.0007501376248798972, 'lambda_l2': 1.9285073574974414, 'max_bin': 569, 'n_estimators': 2029, 'scale_pos_weight': 4.2903951879869595, 'min_child_weight': 4.034183145737675, 'feature_fraction': 0.8422452327959584, 'bagging_fraction': 0.5306161874004248, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:51:25,533] Trial 160 finished with value: 0.7398775020049955 and parameters: {'learning_rate': 0.006303789225759629, 'num_leaves': 26, 'max_depth': 8, 'min_child_samples': 131, 'subsample': 0.9976819709940068, 'colsample_bytree': 0.8240823038356345, 'lambda_l1': 0.0007137985287529019, 'lambda_l2': 1.7259599626022033, 'max_bin': 560, 'n_estimators': 2066, 'scale_pos_weight': 4.217628636592334, 'min_child_weight': 4.374430853899833, 'feature_fraction': 0.8466974759429103, 'bagging_fraction': 0.5293808211640548, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:52:42,009] Trial 161 finished with value: 0.7399729373501598 and parameters: {'learning_rate': 0.005294467672303566, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 138, 'subsample': 0.9889153149101392, 'colsample_bytree': 0.8109470209147621, 'lambda_l1': 0.0012497335371880588, 'lambda_l2': 1.2667470335601099, 'max_bin': 570, 'n_estimators': 1769, 'scale_pos_weight': 4.134238423271773, 'min_child_weight': 2.6140496449608017, 'feature_fraction': 0.8448705241445297, 'bagging_fraction': 0.5076912661954386, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:54:07,164] Trial 162 finished with value: 0.7400076349412539 and parameters: {'learning_rate': 0.005334207152302945, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 138, 'subsample': 0.9897809128567692, 'colsample_bytree': 0.8055939975307487, 'lambda_l1': 0.0011658135561662976, 'lambda_l2': 1.4840049251983785, 'max_bin': 582, 'n_estimators': 1986, 'scale_pos_weight': 4.052476792733052, 'min_child_weight': 2.540173454086649, 'feature_fraction': 0.8660598474038695, 'bagging_fraction': 0.5070645122549878, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:55:30,186] Trial 163 finished with value: 0.7399760461642491 and parameters: {'learning_rate': 0.005334923281861042, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 138, 'subsample': 0.9874717189553467, 'colsample_bytree': 0.8112393158689317, 'lambda_l1': 0.0012016726885625258, 'lambda_l2': 1.504128883148517, 'max_bin': 582, 'n_estimators': 1944, 'scale_pos_weight': 4.177923305739069, 'min_child_weight': 2.5227982867970344, 'feature_fraction': 0.8435898852457198, 'bagging_fraction': 0.5084597834729566, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:56:51,430] Trial 164 finished with value: 0.7399812094760605 and parameters: {'learning_rate': 0.0053933658633278205, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 139, 'subsample': 0.9900012288638305, 'colsample_bytree': 0.8062006632918322, 'lambda_l1': 0.0011145632265657077, 'lambda_l2': 1.551390135365471, 'max_bin': 587, 'n_estimators': 1963, 'scale_pos_weight': 4.025829056658555, 'min_child_weight': 2.5641487572572825, 'feature_fraction': 0.8679708571823682, 'bagging_fraction': 0.5001414039239737, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:58:12,531] Trial 165 finished with value: 0.7400159759996401 and parameters: {'learning_rate': 0.0054274696649704674, 'num_leaves': 25, 'max_depth': 8, 'min_child_samples': 141, 'subsample': 0.9918944363495437, 'colsample_bytree': 0.8538809070497683, 'lambda_l1': 0.0009077786859607611, 'lambda_l2': 1.651804083742618, 'max_bin': 585, 'n_estimators': 1992, 'scale_pos_weight': 4.015803804149133, 'min_child_weight': 2.5543632483668715, 'feature_fraction': 0.8460152645746499, 'bagging_fraction': 0.5005936272947173, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 16:59:29,751] Trial 166 finished with value: 0.7399377832823959 and parameters: {'learning_rate': 0.00610178059692238, 'num_leaves': 23, 'max_depth': 8, 'min_child_samples': 141, 'subsample': 0.9993414040584717, 'colsample_bytree': 0.858315415691303, 'lambda_l1': 0.0008520430546544613, 'lambda_l2': 1.9200296142860334, 'max_bin': 585, 'n_estimators': 1958, 'scale_pos_weight': 4.503262213845477, 'min_child_weight': 3.4663966744731978, 'feature_fraction': 0.8639502368835239, 'bagging_fraction': 0.5003296116354802, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:00:49,809] Trial 167 finished with value: 0.7399775086392955 and parameters: {'learning_rate': 0.005490709017948356, 'num_leaves': 25, 'max_depth': 8, 'min_child_samples': 141, 'subsample': 0.9881931477089466, 'colsample_bytree': 0.8399430671496448, 'lambda_l1': 0.001066276886076363, 'lambda_l2': 1.5229597881363628, 'max_bin': 587, 'n_estimators': 2005, 'scale_pos_weight': 4.064423395673069, 'min_child_weight': 4.804622717034539, 'feature_fraction': 0.882808629334802, 'bagging_fraction': 0.5085601852875916, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:02:17,757] Trial 168 finished with value: 0.7399745365063044 and parameters: {'learning_rate': 0.0056083293526359, 'num_leaves': 25, 'max_depth': 8, 'min_child_samples': 141, 'subsample': 0.9867971433505673, 'colsample_bytree': 0.8786540122624096, 'lambda_l1': 0.0003703892663037016, 'lambda_l2': 1.5439241439650224, 'max_bin': 586, 'n_estimators': 2045, 'scale_pos_weight': 4.0231087938746795, 'min_child_weight': 2.945780924586556, 'feature_fraction': 0.8816891889422925, 'bagging_fraction': 0.5319150800194504, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:03:35,828] Trial 169 finished with value: 0.7398770153736656 and parameters: {'learning_rate': 0.005420353912465632, 'num_leaves': 27, 'max_depth': 8, 'min_child_samples': 70, 'subsample': 0.9902569786619458, 'colsample_bytree': 0.8411933792395836, 'lambda_l1': 0.0012397393748878377, 'lambda_l2': 1.1366132378992528, 'max_bin': 579, 'n_estimators': 1925, 'scale_pos_weight': 4.450660563859282, 'min_child_weight': 2.416901488554569, 'feature_fraction': 0.9024233702686846, 'bagging_fraction': 0.5001241274922771, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:05:03,008] Trial 170 finished with value: 0.7399516342939418 and parameters: {'learning_rate': 0.005000886717166896, 'num_leaves': 26, 'max_depth': 8, 'min_child_samples': 143, 'subsample': 0.9837435845251815, 'colsample_bytree': 0.8181423007268872, 'lambda_l1': 0.0005460594835568216, 'lambda_l2': 1.5976952517869403, 'max_bin': 589, 'n_estimators': 2123, 'scale_pos_weight': 4.924161736964454, 'min_child_weight': 4.167600055320552, 'feature_fraction': 0.8630451879082471, 'bagging_fraction': 0.5083992809367237, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:06:23,608] Trial 171 finished with value: 0.7399544971803526 and parameters: {'learning_rate': 0.005622298466633722, 'num_leaves': 24, 'max_depth': 8, 'min_child_samples': 135, 'subsample': 0.9894498006443966, 'colsample_bytree': 0.8753729753534026, 'lambda_l1': 0.00020155956217191002, 'lambda_l2': 1.5761952403343515, 'max_bin': 572, 'n_estimators': 2028, 'scale_pos_weight': 3.98758348723585, 'min_child_weight': 4.942910378188447, 'feature_fraction': 0.8788231151491463, 'bagging_fraction': 0.5334458091221587, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:07:46,528] Trial 172 finished with value: 0.739957339692961 and parameters: {'learning_rate': 0.005527726305494806, 'num_leaves': 25, 'max_depth': 8, 'min_child_samples': 142, 'subsample': 0.9977935188669399, 'colsample_bytree': 0.8810340511947833, 'lambda_l1': 0.0008914723822250469, 'lambda_l2': 1.8859914880473356, 'max_bin': 585, 'n_estimators': 1992, 'scale_pos_weight': 3.92528978328394, 'min_child_weight': 3.1039275540181577, 'feature_fraction': 0.8444954182703592, 'bagging_fraction': 0.5277158477803425, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:09:12,949] Trial 173 finished with value: 0.7399072786084758 and parameters: {'learning_rate': 0.0059779362185738, 'num_leaves': 29, 'max_depth': 8, 'min_child_samples': 141, 'subsample': 0.9840614007802156, 'colsample_bytree': 0.7715388102321159, 'lambda_l1': 0.0006576562146415087, 'lambda_l2': 0.8912846114140254, 'max_bin': 598, 'n_estimators': 1858, 'scale_pos_weight': 3.621902872633787, 'min_child_weight': 2.581905676912481, 'feature_fraction': 0.8923228600443023, 'bagging_fraction': 0.536970853772531, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:10:21,398] Trial 174 finished with value: 0.7399499525503301 and parameters: {'learning_rate': 0.005348443440086125, 'num_leaves': 25, 'max_depth': 8, 'min_child_samples': 136, 'subsample': 0.9855090604010528, 'colsample_bytree': 0.8514575689880115, 'lambda_l1': 0.0011358745456525217, 'lambda_l2': 1.1260984540993995, 'max_bin': 555, 'n_estimators': 1738, 'scale_pos_weight': 4.133868414414695, 'min_child_weight': 2.8146195014548985, 'feature_fraction': 0.8740182497177569, 'bagging_fraction': 0.5099720277217692, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:11:45,235] Trial 175 finished with value: 0.7398926304797276 and parameters: {'learning_rate': 0.005848461358826285, 'num_leaves': 23, 'max_depth': 8, 'min_child_samples': 132, 'subsample': 0.9926804681919588, 'colsample_bytree': 0.8067966996516451, 'lambda_l1': 0.0003696603546018112, 'lambda_l2': 1.4547498790430382, 'max_bin': 547, 'n_estimators': 2101, 'scale_pos_weight': 4.72001359879173, 'min_child_weight': 3.7586419858156934, 'feature_fraction': 0.8575572583134194, 'bagging_fraction': 0.518498939405747, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:13:25,673] Trial 176 finished with value: 0.739936262460284 and parameters: {'learning_rate': 0.005331250901744523, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 139, 'subsample': 0.9829601382034562, 'colsample_bytree': 0.8366164981375942, 'lambda_l1': 0.0007877730212589881, 'lambda_l2': 1.6144285967994856, 'max_bin': 578, 'n_estimators': 2351, 'scale_pos_weight': 3.64246833099535, 'min_child_weight': 2.334380323066425, 'feature_fraction': 0.9112150455415389, 'bagging_fraction': 0.5258256212534126, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:14:53,593] Trial 177 finished with value: 0.7397173154926628 and parameters: {'learning_rate': 0.005593187074051563, 'num_leaves': 22, 'max_depth': 8, 'min_child_samples': 105, 'subsample': 0.9987003087153384, 'colsample_bytree': 0.8962118455234578, 'lambda_l1': 0.0014544463123469264, 'lambda_l2': 1.0977410659279119, 'max_bin': 565, 'n_estimators': 1930, 'scale_pos_weight': 4.335804513084742, 'min_child_weight': 3.0334440482101135, 'feature_fraction': 0.8489680016290168, 'bagging_fraction': 0.7917943484145621, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:16:10,389] Trial 178 finished with value: 0.7399623960939653 and parameters: {'learning_rate': 0.006149171322994729, 'num_leaves': 28, 'max_depth': 8, 'min_child_samples': 143, 'subsample': 0.9793298249071039, 'colsample_bytree': 0.8521228198705223, 'lambda_l1': 0.0010899276265773539, 'lambda_l2': 1.958998803291562, 'max_bin': 588, 'n_estimators': 1680, 'scale_pos_weight': 4.00851126458836, 'min_child_weight': 3.0067383672391057, 'feature_fraction': 0.8080772371674162, 'bagging_fraction': 0.5108477178457745, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:17:24,813] Trial 179 finished with value: 0.7398815920208812 and parameters: {'learning_rate': 0.005637442218363411, 'num_leaves': 25, 'max_depth': 8, 'min_child_samples': 128, 'subsample': 0.9996265345409459, 'colsample_bytree': 0.7933477120061575, 'lambda_l1': 0.00040047367897233483, 'lambda_l2': 1.3420453879775356, 'max_bin': 572, 'n_estimators': 1810, 'scale_pos_weight': 4.601970491229808, 'min_child_weight': 4.841942928601437, 'feature_fraction': 0.9240453257483364, 'bagging_fraction': 0.5385886936688176, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:18:55,426] Trial 180 finished with value: 0.7399685483847287 and parameters: {'learning_rate': 0.0052614620122176745, 'num_leaves': 27, 'max_depth': 8, 'min_child_samples': 141, 'subsample': 0.9795977584407457, 'colsample_bytree': 0.8153532798194162, 'lambda_l1': 0.0005410464316160682, 'lambda_l2': 1.9969835636081115, 'max_bin': 550, 'n_estimators': 2084, 'scale_pos_weight': 3.5375853998970057, 'min_child_weight': 2.136813500475875, 'feature_fraction': 0.8682661675726977, 'bagging_fraction': 0.5260197727511741, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:20:06,101] Trial 181 finished with value: 0.7399500481402684 and parameters: {'learning_rate': 0.006421956897904559, 'num_leaves': 29, 'max_depth': 8, 'min_child_samples': 139, 'subsample': 0.9867865052429917, 'colsample_bytree': 0.8260827073759571, 'lambda_l1': 0.0009813873822253718, 'lambda_l2': 0.9651382658181062, 'max_bin': 541, 'n_estimators': 1639, 'scale_pos_weight': 3.795138199129039, 'min_child_weight': 1.8904951872880529, 'feature_fraction': 0.8860970205771544, 'bagging_fraction': 0.5098199873941357, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.
[I 2025-02-26 17:21:28,946] Trial 182 finished with value: 0.7399339317591517 and parameters: {'learning_rate': 0.005950100766872215, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 137, 'subsample': 0.7623072401263794, 'colsample_bytree': 0.8059381031179221, 'lambda_l1': 0.001335371687814692, 'lambda_l2': 0.6904293933647502, 'max_bin': 557, 'n_estimators': 1969, 'scale_pos_weight': 3.7890051291787326, 'min_child_weight': 3.8768867128993225, 'feature_fraction': 0.8400068581509073, 'bagging_fraction': 0.5001235552314611, 'bagging_freq': 2}. Best is trial 130 with value: 0.7400296340017085.

{'learning_rate': 0.006192984010225524, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 145, 'subsample': 0.9530598170006493, 'colsample_bytree': 0.7637820484562927, 'lambda_l1': 0.00010612350732401384, 'lambda_l2': 1.9403017534727327, 'max_bin': 555, 'n_estimators': 1746, 'scale_pos_weight': 2.952421231501966, 'min_child_weight': 2.2003992924152467, 'feature_fraction': 0.7373377710707284, 'bagging_fraction': 0.5426901866174296, 'bagging_freq': 2} 0.7400376427126525

In [28]:
study.optimize(lambda trial: objective(trial, top5_df['ratio'][0], top5_df['model'][0]), n_trials=100)

params, auc = study.best_params, study.best_value
print(params, auc)
top5_df.loc[0, ['param', 'tuned_auc']] =  params, auc


# Study 저장
with open("./data/optuna_study_300.pkl", "wb") as f:
    pickle.dump(study, f)

# Study 불러오기
with open("./data/optuna_study_300.pkl", "rb") as f:
    study = pickle.load(f)

[I 2025-02-26 20:14:21,903] Trial 250 finished with value: 0.7397652803202472 and parameters: {'learning_rate': 0.005211623906465605, 'num_leaves': 64, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9904629382061906, 'colsample_bytree': 0.8837588823478838, 'lambda_l1': 0.00033387480482500434, 'lambda_l2': 1.6203961252289103, 'max_bin': 600, 'n_estimators': 1910, 'scale_pos_weight': 3.564629600125515, 'min_child_weight': 4.751489866363486, 'feature_fraction': 0.8106257988650707, 'bagging_fraction': 0.5104587866282918, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:15:48,348] Trial 251 finished with value: 0.7399784665137094 and parameters: {'learning_rate': 0.0050564095549366665, 'num_leaves': 34, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9755805032123083, 'colsample_bytree': 0.8809672555389535, 'lambda_l1': 0.0003713641103182995, 'lambda_l2': 0.0013605023438443985, 'max_bin': 592, 'n_estimators': 1828, 'scale_pos_weight': 3.765700825235816, 'min_child_weight': 4.818079604634797, 'feature_fraction': 0.8341705958874402, 'bagging_fraction': 0.5240355723697724, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:17:18,869] Trial 252 finished with value: 0.7399528381613559 and parameters: {'learning_rate': 0.0054755984734883075, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9999890644771438, 'colsample_bytree': 0.8928607231994258, 'lambda_l1': 0.00042438446994567567, 'lambda_l2': 1.6162162151702946, 'max_bin': 586, 'n_estimators': 1967, 'scale_pos_weight': 3.4962796509789356, 'min_child_weight': 1.989359289673305, 'feature_fraction': 0.8182601144976835, 'bagging_fraction': 0.5106610629567053, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:18:37,508] Trial 253 finished with value: 0.7399944559991652 and parameters: {'learning_rate': 0.005005068590669694, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 144, 'subsample': 0.9832915426846761, 'colsample_bytree': 0.8703611187827165, 'lambda_l1': 0.00042940276523141427, 'lambda_l2': 1.6381805210207585, 'max_bin': 592, 'n_estimators': 1787, 'scale_pos_weight': 3.804628503070537, 'min_child_weight': 1.6251011565223454, 'feature_fraction': 0.8071163084329115, 'bagging_fraction': 0.5289223280466719, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:20:01,288] Trial 254 finished with value: 0.7399804775397196 and parameters: {'learning_rate': 0.0054920185207640694, 'num_leaves': 35, 'max_depth': 9, 'min_child_samples': 142, 'subsample': 0.9727076892154007, 'colsample_bytree': 0.9062883704976709, 'lambda_l1': 0.00018074815362058302, 'lambda_l2': 1.33094796582784, 'max_bin': 600, 'n_estimators': 1806, 'scale_pos_weight': 3.9054964529797034, 'min_child_weight': 2.459650046891045, 'feature_fraction': 0.7995209197579676, 'bagging_fraction': 0.5060292730292162, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:21:28,956] Trial 255 finished with value: 0.7399875517241823 and parameters: {'learning_rate': 0.005570469969122263, 'num_leaves': 33, 'max_depth': 8, 'min_child_samples': 140, 'subsample': 0.9906790730442303, 'colsample_bytree': 0.8660576602833794, 'lambda_l1': 0.0005129811483148424, 'lambda_l2': 0.9220022799652831, 'max_bin': 586, 'n_estimators': 1907, 'scale_pos_weight': 3.6504424509088342, 'min_child_weight': 3.4671446967713546, 'feature_fraction': 0.8238905359990162, 'bagging_fraction': 0.517716644575244, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:22:38,140] Trial 256 finished with value: 0.7303868468742858 and parameters: {'learning_rate': 0.057153015843005806, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 145, 'subsample': 0.9834685767544041, 'colsample_bytree': 0.8852845162308807, 'lambda_l1': 0.00020837127350828788, 'lambda_l2': 1.5497438402014654, 'max_bin': 592, 'n_estimators': 1747, 'scale_pos_weight': 3.390470424006577, 'min_child_weight': 4.1443710777004, 'feature_fraction': 0.8123983584572907, 'bagging_fraction': 0.50079415687431, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:24:07,834] Trial 257 finished with value: 0.7399693649773048 and parameters: {'learning_rate': 0.005315085024121809, 'num_leaves': 33, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.972530160137026, 'colsample_bytree': 0.8013783967344449, 'lambda_l1': 0.0005721013773685254, 'lambda_l2': 1.6600936765423817, 'max_bin': 552, 'n_estimators': 2034, 'scale_pos_weight': 3.598092673420764, 'min_child_weight': 2.7768707292228076, 'feature_fraction': 0.8506331718316174, 'bagging_fraction': 0.5319671153425591, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:25:31,438] Trial 258 finished with value: 0.7400214945040295 and parameters: {'learning_rate': 0.005294885629074437, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 147, 'subsample': 0.9910363111805613, 'colsample_bytree': 0.8240747712970841, 'lambda_l1': 0.0003262010773842707, 'lambda_l2': 1.1735685886082754, 'max_bin': 532, 'n_estimators': 1914, 'scale_pos_weight': 3.3590775271159212, 'min_child_weight': 2.2493799105559953, 'feature_fraction': 0.793126884867176, 'bagging_fraction': 0.5206208345722702, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:27:02,094] Trial 259 finished with value: 0.7399966602130579 and parameters: {'learning_rate': 0.005009748412861629, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 147, 'subsample': 0.9906897091636577, 'colsample_bytree': 0.8296159732384525, 'lambda_l1': 0.00030569871521670674, 'lambda_l2': 0.7373490961689867, 'max_bin': 543, 'n_estimators': 2103, 'scale_pos_weight': 3.303618030452784, 'min_child_weight': 1.9499151940170227, 'feature_fraction': 0.793602437917269, 'bagging_fraction': 0.5206380641085709, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:28:23,748] Trial 260 finished with value: 0.7398518680946797 and parameters: {'learning_rate': 0.005606825156873626, 'num_leaves': 34, 'max_depth': 8, 'min_child_samples': 60, 'subsample': 0.9991602658909735, 'colsample_bytree': 0.8399724397191088, 'lambda_l1': 0.00045625081576409387, 'lambda_l2': 1.0549784342708037, 'max_bin': 530, 'n_estimators': 1955, 'scale_pos_weight': 3.3912245597100634, 'min_child_weight': 2.312912669906816, 'feature_fraction': 0.7870994300370355, 'bagging_fraction': 0.5313832767196156, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:30:45,972] Trial 261 finished with value: 0.7394256681106895 and parameters: {'learning_rate': 0.00574587832176636, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 144, 'subsample': 0.9900041630692963, 'colsample_bytree': 0.8179673773486613, 'lambda_l1': 0.0008086161260450641, 'lambda_l2': 1.2360668581382293, 'max_bin': 318, 'n_estimators': 3311, 'scale_pos_weight': 3.2961755815621983, 'min_child_weight': 1.7086055526588897, 'feature_fraction': 0.8056302090870748, 'bagging_fraction': 0.5372998163720797, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:32:04,585] Trial 262 finished with value: 0.7400131719288436 and parameters: {'learning_rate': 0.005461467193761309, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 148, 'subsample': 0.9825569278652928, 'colsample_bytree': 0.8273293667887998, 'lambda_l1': 0.00023818861284971175, 'lambda_l2': 0.951703206040617, 'max_bin': 553, 'n_estimators': 1877, 'scale_pos_weight': 3.434378126724123, 'min_child_weight': 2.2984764197156955, 'feature_fraction': 0.83442813826747, 'bagging_fraction': 0.5092300220739922, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:33:25,780] Trial 263 finished with value: 0.7399940630222721 and parameters: {'learning_rate': 0.005331818230345224, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9829484320082857, 'colsample_bytree': 0.8288202796097874, 'lambda_l1': 0.0002550149627729205, 'lambda_l2': 1.3607767548210201, 'max_bin': 533, 'n_estimators': 1880, 'scale_pos_weight': 3.1400462857516525, 'min_child_weight': 2.217412435499157, 'feature_fraction': 0.8447279363722886, 'bagging_fraction': 0.5069026683383797, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:34:49,549] Trial 264 finished with value: 0.7380444188350379 and parameters: {'learning_rate': 0.014831925520650154, 'num_leaves': 34, 'max_depth': 8, 'min_child_samples': 146, 'subsample': 0.999266897094797, 'colsample_bytree': 0.8200027510159726, 'lambda_l1': 1.2445376587704757, 'lambda_l2': 0.8363987267402613, 'max_bin': 542, 'n_estimators': 1990, 'scale_pos_weight': 3.8650722151319536, 'min_child_weight': 2.626159727234068, 'feature_fraction': 0.8313630592013302, 'bagging_fraction': 0.5104247158832295, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:36:11,854] Trial 265 finished with value: 0.7399865870124749 and parameters: {'learning_rate': 0.005708169558239718, 'num_leaves': 35, 'max_depth': 8, 'min_child_samples': 148, 'subsample': 0.9844860917173717, 'colsample_bytree': 0.8066956166038699, 'lambda_l1': 0.000332327898153017, 'lambda_l2': 1.3549994193419184, 'max_bin': 553, 'n_estimators': 1859, 'scale_pos_weight': 3.221002049258847, 'min_child_weight': 3.077382353805346, 'feature_fraction': 0.8554284143854964, 'bagging_fraction': 0.5217303525556145, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:37:31,695] Trial 266 finished with value: 0.7399989191568276 and parameters: {'learning_rate': 0.00530329071961705, 'num_leaves': 24, 'max_depth': 8, 'min_child_samples': 148, 'subsample': 0.7838351978495963, 'colsample_bytree': 0.8403319689655346, 'lambda_l1': 0.0006598157666273967, 'lambda_l2': 0.6857454390452484, 'max_bin': 241, 'n_estimators': 2136, 'scale_pos_weight': 3.501190727918229, 'min_child_weight': 2.103270734536711, 'feature_fraction': 0.7941365493822945, 'bagging_fraction': 0.5009694220503915, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:38:43,191] Trial 267 finished with value: 0.7275719496293152 and parameters: {'learning_rate': 0.07648461974179163, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 142, 'subsample': 0.9740135056707198, 'colsample_bytree': 0.8266488940542485, 'lambda_l1': 0.00024993923756372295, 'lambda_l2': 0.9293226499152177, 'max_bin': 537, 'n_estimators': 1708, 'scale_pos_weight': 3.0411128948083817, 'min_child_weight': 2.5863912207326667, 'feature_fraction': 0.8406071936073779, 'bagging_fraction': 0.5169055592601626, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:39:54,839] Trial 268 finished with value: 0.7399770888468729 and parameters: {'learning_rate': 0.005027070628620656, 'num_leaves': 22, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9903433197997066, 'colsample_bytree': 0.845511729908089, 'lambda_l1': 0.0008779660951988353, 'lambda_l2': 1.655998945178272, 'max_bin': 572, 'n_estimators': 1977, 'scale_pos_weight': 2.706356847688942, 'min_child_weight': 1.5532438300262696, 'feature_fraction': 0.836214685401307, 'bagging_fraction': 0.5247500740954737, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:41:10,049] Trial 269 finished with value: 0.7399739871777054 and parameters: {'learning_rate': 0.005676025996336255, 'num_leaves': 29, 'max_depth': 8, 'min_child_samples': 145, 'subsample': 0.9719912244494031, 'colsample_bytree': 0.8203274890401875, 'lambda_l1': 0.00034829144260180696, 'lambda_l2': 1.1646636859964086, 'max_bin': 554, 'n_estimators': 1825, 'scale_pos_weight': 3.3877318923089197, 'min_child_weight': 3.347477821257191, 'feature_fraction': 0.7855385375894216, 'bagging_fraction': 0.5106824397223447, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:42:17,398] Trial 270 finished with value: 0.7399680988878241 and parameters: {'learning_rate': 0.0053732165923343145, 'num_leaves': 33, 'max_depth': 8, 'min_child_samples': 140, 'subsample': 0.982743747739387, 'colsample_bytree': 0.8759147829530738, 'lambda_l1': 0.0004922339648008075, 'lambda_l2': 1.991675563980565, 'max_bin': 561, 'n_estimators': 1689, 'scale_pos_weight': 3.921405791072721, 'min_child_weight': 1.9370193366590769, 'feature_fraction': 0.800948165344768, 'bagging_fraction': 0.5315421112366528, 'bagging_freq': 5}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:44:14,527] Trial 271 finished with value: 0.7396278196887895 and parameters: {'learning_rate': 0.005937968306812629, 'num_leaves': 32, 'max_depth': 9, 'min_child_samples': 147, 'subsample': 0.9999843048931789, 'colsample_bytree': 0.8641114283721315, 'lambda_l1': 0.00022103509056429203, 'lambda_l2': 1.42738053278168, 'max_bin': 583, 'n_estimators': 2818, 'scale_pos_weight': 3.6873067502270636, 'min_child_weight': 2.3339007034522474, 'feature_fraction': 0.825694816903901, 'bagging_fraction': 0.5180393680580045, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:45:41,165] Trial 272 finished with value: 0.7399816582626026 and parameters: {'learning_rate': 0.005474502620695778, 'num_leaves': 30, 'max_depth': 8, 'min_child_samples': 143, 'subsample': 0.9903965448513373, 'colsample_bytree': 0.8023903896168977, 'lambda_l1': 0.0015556424512987092, 'lambda_l2': 1.6773841521725905, 'max_bin': 546, 'n_estimators': 2049, 'scale_pos_weight': 3.0858430220584756, 'min_child_weight': 2.9401535780702335, 'feature_fraction': 0.8522664164351716, 'bagging_fraction': 0.5065542520598605, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:46:54,858] Trial 273 finished with value: 0.7399725396208133 and parameters: {'learning_rate': 0.005816619297622154, 'num_leaves': 25, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9695403472147949, 'colsample_bytree': 0.8762143098709961, 'lambda_l1': 0.0003002452542475757, 'lambda_l2': 0.986016361876645, 'max_bin': 178, 'n_estimators': 1892, 'scale_pos_weight': 3.2530250416927844, 'min_child_weight': 3.482750745144376, 'feature_fraction': 0.8137410139945622, 'bagging_fraction': 0.527127109819094, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:48:09,354] Trial 274 finished with value: 0.7389387720399443 and parameters: {'learning_rate': 0.012743094379465898, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 89, 'subsample': 0.979153089622683, 'colsample_bytree': 0.834239999830651, 'lambda_l1': 0.0002137045150044141, 'lambda_l2': 1.2502799234308066, 'max_bin': 574, 'n_estimators': 1781, 'scale_pos_weight': 2.837162615291823, 'min_child_weight': 2.676131318840489, 'feature_fraction': 0.7926149337808107, 'bagging_fraction': 0.5378400918050735, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:49:23,057] Trial 275 finished with value: 0.7400311557509756 and parameters: {'learning_rate': 0.0052635880798424985, 'num_leaves': 36, 'max_depth': 8, 'min_child_samples': 147, 'subsample': 0.9919426585370306, 'colsample_bytree': 0.8129516429151094, 'lambda_l1': 0.0009371601654455616, 'lambda_l2': 1.432698099641424, 'max_bin': 532, 'n_estimators': 1646, 'scale_pos_weight': 3.5497283835853226, 'min_child_weight': 2.21980402682278, 'feature_fraction': 0.8034420922488769, 'bagging_fraction': 0.5158894838356328, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:50:41,022] Trial 276 finished with value: 0.7399808156219034 and parameters: {'learning_rate': 0.005034368093090368, 'num_leaves': 36, 'max_depth': 8, 'min_child_samples': 147, 'subsample': 0.9676244359986705, 'colsample_bytree': 0.8477809074693411, 'lambda_l1': 0.0006602726826756018, 'lambda_l2': 1.0187122242722102, 'max_bin': 533, 'n_estimators': 1669, 'scale_pos_weight': 3.4495626887271347, 'min_child_weight': 1.8087069758246896, 'feature_fraction': 0.8040784269953437, 'bagging_fraction': 0.5095842900071456, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:51:51,547] Trial 277 finished with value: 0.7399878081568539 and parameters: {'learning_rate': 0.006424127599171241, 'num_leaves': 33, 'max_depth': 8, 'min_child_samples': 146, 'subsample': 0.9794070455730117, 'colsample_bytree': 0.8146583838951448, 'lambda_l1': 0.48303768895209864, 'lambda_l2': 1.4184443313199935, 'max_bin': 524, 'n_estimators': 1559, 'scale_pos_weight': 2.9890888624521246, 'min_child_weight': 2.2335843685204653, 'feature_fraction': 0.7881232645628885, 'bagging_fraction': 0.5247714774022509, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:53:04,326] Trial 278 finished with value: 0.7400145973826189 and parameters: {'learning_rate': 0.005539740952200795, 'num_leaves': 35, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9886821955719586, 'colsample_bytree': 0.7546824232554677, 'lambda_l1': 0.0008521142633520009, 'lambda_l2': 1.183274124333273, 'max_bin': 599, 'n_estimators': 1634, 'scale_pos_weight': 4.190636138236528, 'min_child_weight': 1.5560180943625295, 'feature_fraction': 0.7986624997596412, 'bagging_fraction': 0.5016451602165886, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:54:17,240] Trial 279 finished with value: 0.7400320979434886 and parameters: {'learning_rate': 0.005908811909665145, 'num_leaves': 38, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9893844829450502, 'colsample_bytree': 0.8627608640398844, 'lambda_l1': 0.0010157471244413698, 'lambda_l2': 0.6376602223248128, 'max_bin': 600, 'n_estimators': 1470, 'scale_pos_weight': 4.241960698719777, 'min_child_weight': 1.5604794809194025, 'feature_fraction': 0.7996581921873148, 'bagging_fraction': 0.5033478258128757, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:55:19,929] Trial 280 finished with value: 0.7399565706423596 and parameters: {'learning_rate': 0.006154380877503152, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 150, 'subsample': 0.9911000410069459, 'colsample_bytree': 0.7501439572352255, 'lambda_l1': 0.000930797516097951, 'lambda_l2': 0.7288284609404331, 'max_bin': 594, 'n_estimators': 1438, 'scale_pos_weight': 4.587032494296815, 'min_child_weight': 1.1280539161772347, 'feature_fraction': 0.8036585832735784, 'bagging_fraction': 0.5008716728041726, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:56:27,791] Trial 281 finished with value: 0.7400047331105968 and parameters: {'learning_rate': 0.005634098050004645, 'num_leaves': 35, 'max_depth': 8, 'min_child_samples': 148, 'subsample': 0.9896045701278263, 'colsample_bytree': 0.8676701739518593, 'lambda_l1': 0.0005626990121496275, 'lambda_l2': 0.5897613429250794, 'max_bin': 599, 'n_estimators': 1488, 'scale_pos_weight': 4.399997353415573, 'min_child_weight': 1.408950511774985, 'feature_fraction': 0.7969301346251758, 'bagging_fraction': 0.501980727330678, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.
[I 2025-02-26 20:57:36,624] Trial 282 finished with value: 0.739942543118198 and parameters: {'learning_rate': 0.006350512636735325, 'num_leaves': 38, 'max_depth': 8, 'min_child_samples': 145, 'subsample': 0.990172128975706, 'colsample_bytree': 0.8668793067226276, 'lambda_l1': 0.000537108735245692, 'lambda_l2': 0.6671682755072329, 'max_bin': 598, 'n_estimators': 1395, 'scale_pos_weight': 4.352598031530652, 'min_child_weight': 1.1871586061740116, 'feature_fraction': 0.7954795366587605, 'bagging_fraction': 0.5059274575915876, 'bagging_freq': 2}. Best is trial 200 with value: 0.7400376427126525.

{'learning_rate': 0.005404665080038044, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 142, 'subsample': 0.6651803742719826, 'colsample_bytree': 0.7685478000166595, 'lambda_l1': 2.081721942205924, 'lambda_l2': 1.9845698568428882, 'max_bin': 552, 'n_estimators': 1692, 'scale_pos_weight': 3.574385124249283, 'min_child_weight': 2.9798133779257356, 'feature_fraction': 0.8194483752728194, 'bagging_fraction': 0.5203599421398333, 'bagging_freq': 2} 0.740060511984433

In [30]:
optuna.visualization.plot_param_importances(study) # 파라미터 중요도 확인 그래프

In [31]:
optuna.visualization.plot_optimization_history(study) # 최적화 과정 시각화

In [38]:
optuna_resuit = study.trials_dataframe()
optuna_resuit.sort_values(by='value', ascending=False).head()
optuna_top5 = optuna_resuit.sort_values(by='value', ascending=False).head()
optuna_top5

,number,value,datetime_start,datetime_complete,duration,params_bagging_fraction,params_bagging_freq,params_colsample_bytree,params_feature_fraction,params_lambda_l1,...,params_learning_rate,params_max_bin,params_max_depth,params_min_child_samples,params_min_child_weight,params_n_estimators,params_num_leaves,params_scale_pos_weight,params_subsample,state
305,305,0.740061,2025-02-26 21:28:32.068625,2025-02-26 21:29:57.379140,0 days 00:01:25.310515,0.520360,2,0.768548,0.819448,2.081722,...,0.005405,552,8,142,2.979813,1692,37,3.574385,0.665180,COMPLETE
342,342,0.740054,2025-02-26 22:21:20.878897,2025-02-26 22:22:41.656732,0 days 00:01:20.777835,0.518023,2,0.875145,0.829536,3.186385,...,0.005241,529,8,136,4.120454,1820,37,3.365979,0.831631,COMPLETE
312,312,0.740048,2025-02-26 21:38:15.751547,2025-02-26 21:39:37.617309,0 days 00:01:21.865762,0.540985,2,0.772574,0.778605,4.763991,...,0.005871,526,8,147,3.098251,1653,35,3.284882,0.963527,COMPLETE
301,301,0.740044,2025-02-26 21:23:50.413315,2025-02-26 21:25:12.159272,0 days 00:01:21.745957,0.516934,2,0.800321,0.802347,0.905354,...,0.005347,550,8,142,3.621465,1685,37,3.821925,0.999113,COMPLETE
338,338,0.740038,2025-02-26 22:16:00.147206,2025-02-26 22:17:21.713531,0 days 00:01:21.566325,0.516469,2,0.852843,0.817527,4.045080,...,0.005004,522,8,140,4.823583,1781,36,3.332666,0.776001,COMPLETE

In [50]:
# train 데이터를 5개로 나누어 교차 검증
under_ratio_df = pd.DataFrame(columns=['fold', "model_num", 'auc'])

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
for i, index in enumerate(skf.split(X, y)):
    # 데이터 분할
    print(f"Fold {i + 1}")
    X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
    y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
    print(Counter(y_train), Counter(y_val))


    param_1 = {'learning_rate': 0.005404665080038044, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 142, 'subsample': 0.6651803742719826, 'colsample_bytree': 0.7685478000166595, 'lambda_l1': 2.081721942205924, 'lambda_l2': 1.9845698568428882, 'max_bin': 552, 'n_estimators': 1692, 'scale_pos_weight': 3.574385124249283, 'min_child_weight': 2.9798133779257356, 'feature_fraction': 0.8194483752728194, 'bagging_fraction': 0.5203599421398333, 'bagging_freq': 2}
    param_2 = {'learning_rate': 0.005241044750009647, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 136, 'subsample': 0.8316305241255582, 'colsample_bytree': 0.8751454304107738, 'lambda_l1': 3.1863847267496954, 'lambda_l2': 1.9599348709473319, 'max_bin': 529, 'n_estimators': 1820, 'scale_pos_weight': 3.3659790014660134, 'min_child_weight': 4.120453976315193, 'feature_fraction': 0.8295361659356961, 'bagging_fraction': 0.5180226651099835, 'bagging_freq': 2}
    param_3 = {'learning_rate': 0.005870648662761175, 'num_leaves': 35, 'max_depth': 8, 'min_child_samples': 147, 'subsample': 0.963526863489085, 'colsample_bytree': 0.7725737353035547, 'lambda_l1': 4.763990765216757, 'lambda_l2': 1.4307728513570679, 'max_bin': 526, 'n_estimators': 1653, 'scale_pos_weight': 3.2848819311587154, 'min_child_weight': 3.0982512723205846, 'feature_fraction': 0.7786049991397331, 'bagging_fraction': 0.5409850381444363, 'bagging_freq': 2}
    
    param_4 = {'learning_rate': 0.005346878637366447, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 142, 'subsample': 0.9991125920471303, 'colsample_bytree': 0.8003207366208486, 'lambda_l1': 0.9053542803984748, 'lambda_l2': 1.381697200704866, 'max_bin': 550, 'n_estimators': 1685, 'scale_pos_weight': 3.8219254462472905, 'min_child_weight': 3.6214646053600323, 'feature_fraction': 0.8023473252909493, 'bagging_fraction': 0.516934474617231, 'bagging_freq': 2}
    param_5 = {'learning_rate': 0.005241044750009647, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 136, 'subsample': 0.8316305241255582, 'colsample_bytree': 0.8751454304107738, 'lambda_l1': 3.1863847267496954, 'lambda_l2': 1.9599348709473319, 'max_bin': 529, 'n_estimators': 1820, 'scale_pos_weight': 3.3659790014660134, 'min_child_weight': 4.120453976315193, 'feature_fraction': 0.8295361659356961, 'bagging_fraction': 0.5180226651099835, 'bagging_freq': 2}

    import lightgbm as lgb
    model_1 = lgb.LGBMClassifier(**param_1, random_state=RANDOM_STATE, n_jobs=-1)
    model_2 = lgb.LGBMClassifier(**param_2, random_state=RANDOM_STATE, n_jobs=-1)
    model_3 = lgb.LGBMClassifier(**param_3, random_state=RANDOM_STATE, n_jobs=-1)
    model_4 = lgb.LGBMClassifier(**param_4, random_state=RANDOM_STATE, n_jobs=-1)
    model_5 = lgb.LGBMClassifier(**param_5, random_state=RANDOM_STATE, n_jobs=-1)

    model_1.fit(X_train, y_train)
    model_2.fit(X_train, y_train)
    model_3.fit(X_train, y_train)
    model_4.fit(X_train, y_train)
    model_5.fit(X_train, y_train)

    y_proba_1 = model_1.predict_proba(X_val)[:, 1]
    y_proba_2 = model_2.predict_proba(X_val)[:, 1]
    y_proba_3 = model_3.predict_proba(X_val)[:, 1]
    y_proba_4 = model_4.predict_proba(X_val)[:, 1]
    y_proba_5 = model_5.predict_proba(X_val)[:, 1]

    auc_1 = roc_auc_score(y_val, y_proba_1)
    auc_2 = roc_auc_score(y_val, y_proba_2)
    auc_3 = roc_auc_score(y_val, y_proba_3)
    auc_4 = roc_auc_score(y_val, y_proba_4)
    auc_5 = roc_auc_score(y_val, y_proba_5)

    under_ratio_df.loc[len(under_ratio_df), :] = [i+1, 1, auc_1]
    under_ratio_df.loc[len(under_ratio_df), :] = [i+1, 2, auc_2]
    under_ratio_df.loc[len(under_ratio_df), :] = [i+1, 3, auc_3]
    under_ratio_df.loc[len(under_ratio_df), :] = [i+1, 4, auc_4]
    under_ratio_df.loc[len(under_ratio_df), :] = [i+1, 5, auc_5]

    model_1_pred = model_1.predict_proba(X_val)[:, 1]
    model_2_pred = model_2.predict_proba(X_val)[:, 1]
    model_3_pred = model_3.predict_proba(X_val)[:, 1]
    model_4_pred = model_4.predict_proba(X_val)[:, 1]
    model_5_pred = model_5.predict_proba(X_val)[:, 1]

    # ensemble_pred = (model_1_pred + model_2_pred + model_3_pred + model_4_pred + model_5_pred) / 5
    ensemble_pred = (model_1_pred + model_2_pred + model_3_pred) / 3
    ensemble_auc = roc_auc_score(y_val, ensemble_pred)
    under_ratio_df.loc[len(under_ratio_df), :] = [i+1, 'ensemble', ensemble_auc]

Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})

In [51]:
under_ratio_df.groupby(["model_num"]).mean()[['auc']]

                auc
model_num
1          0.740061
2          0.740054
3          0.740048
4          0.740044
5          0.740054
ensemble   0.740078

In [42]:
under_ratio_df.groupby(["model_num"]).mean()[['auc']]

                auc
model_num
1          0.740061
2          0.740054
3          0.740048
4          0.740044
5          0.740054
ensemble   0.740077

### 최종 예측

단일

In [41]:
top5_df

     ratio           model       auc
0  default  LGBMClassifier  0.738864
1        2  LGBMClassifier   0.73852
2      ros  LGBMClassifier  0.738255
3        1  LGBMClassifier   0.73778
4  default   XGBClassifier  0.735134

In [45]:
top5_df

,ratio,model,auc,param,tuned_auc
0,default,LGBMClassifier,0.738864,"{'learning_rate': 0.005404665080038044, 'num_l...",0.740061
1,2,LGBMClassifier,0.73852,NaN,NaN
2,ros,LGBMClassifier,0.738255,NaN,NaN
3,1,LGBMClassifier,0.73778,NaN,NaN
4,default,XGBClassifier,0.735134,NaN,NaN

In [46]:
# train_data에서 임신 성공 여부을 제외한 모든 열을 feature로 사용
X = train_encoded.drop(columns=["임신 성공 여부"])
y = train_encoded["임신 성공 여부"]


print('샘플링 진행')
best_ratio = top5_df.loc[0, 'ratio']
print(best_ratio)
if best_ratio == 'default':
    X_sample, y_sample = X, y

elif best_ratio == 'ros':
    ros = RandomOverSampler(random_state=RANDOM_STATE)
    X_ros, y_ros = ros.fit_resample(X, y)
    print("Random Oversampling 클래스 비율:", Counter(y_ros))
    X_sample, y_sample = X_ros, y_ros 
else:
    normal_ratio = best_ratio
    df_normal = train_encoded[train_encoded["임신 성공 여부"] == 0]
    df_abnormal = train_encoded[train_encoded["임신 성공 여부"] == 1]
    print(f"Total: Normal: {len(df_normal)}, AbNormal: {len(df_abnormal)}")

    df_normal = df_normal.sample(n=int(len(df_abnormal) * normal_ratio), replace=False, random_state=RANDOM_STATE)
    df_concat = pd.concat([df_normal, df_abnormal], axis=0).reset_index(drop=True)
    X_sample, y_sample = df_concat.drop(columns=["임신 성공 여부"]), df_concat["임신 성공 여부"]

import xgboost as xgb
import lightgbm as lgb
import catboost as cat

param = top5_df.loc[0, 'param']
if top5_df.loc[0, 'model'] == 'XGBClassifier':
    model = xgb.XGBClassifier(**param, random_state=RANDOM_STATE, n_jobs=-1)
elif top5_df.loc[0, 'model'] == 'LGBMClassifier':
    model = lgb.LGBMClassifier(**param, random_state=RANDOM_STATE, n_jobs=-1)
elif top5_df.loc[0, 'model'] == 'CatBoostClassifier':
    model =  cat.CatBoostClassifier(**param, random_state=RANDOM_STATE, auto_class_weights="Balanced")

model.fit(X_sample, y_sample)
test_proba = model.predict_proba(test_encoded)[:, 1]
test_proba

샘플링 진행
default

array([0.00297803, 0.00247761, 0.38668116, ..., 0.76264853, 0.44227659,
       0.00298511])

In [47]:
sample_submission = pd.read_csv('./data/sample_submission.csv')
sample_submission['probability'] = test_proba
sample_submission.to_csv('./data/튜닝_안나누기_단일_후처리_랜덤수정_350.csv', index=False)

In [48]:
temp_list = ['난자 저장용',  '기증용']
# '기증용, 배아 저장용'
sample_submission.loc[test[test['배아 생성 주요 이유'].isin(temp_list)].index, 'probability'] = 0
sample_submission.loc[test[test['시술 당시 나이'] == -1].index, 'probability'] = 0

In [49]:
sample_submission.to_csv('./data/튜닝_안나누기_단일_후처리_랜덤수정_350.csv', index=False)

In [52]:
# train_data에서 임신 성공 여부을 제외한 모든 열을 feature로 사용
X = train_encoded.drop(columns=["임신 성공 여부"])
y = train_encoded["임신 성공 여부"]

param_1 = {'learning_rate': 0.005404665080038044, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 142, 'subsample': 0.6651803742719826, 'colsample_bytree': 0.7685478000166595, 'lambda_l1': 2.081721942205924, 'lambda_l2': 1.9845698568428882, 'max_bin': 552, 'n_estimators': 1692, 'scale_pos_weight': 3.574385124249283, 'min_child_weight': 2.9798133779257356, 'feature_fraction': 0.8194483752728194, 'bagging_fraction': 0.5203599421398333, 'bagging_freq': 2}
param_2 = {'learning_rate': 0.005241044750009647, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 136, 'subsample': 0.8316305241255582, 'colsample_bytree': 0.8751454304107738, 'lambda_l1': 3.1863847267496954, 'lambda_l2': 1.9599348709473319, 'max_bin': 529, 'n_estimators': 1820, 'scale_pos_weight': 3.3659790014660134, 'min_child_weight': 4.120453976315193, 'feature_fraction': 0.8295361659356961, 'bagging_fraction': 0.5180226651099835, 'bagging_freq': 2}
param_3 = {'learning_rate': 0.005870648662761175, 'num_leaves': 35, 'max_depth': 8, 'min_child_samples': 147, 'subsample': 0.963526863489085, 'colsample_bytree': 0.7725737353035547, 'lambda_l1': 4.763990765216757, 'lambda_l2': 1.4307728513570679, 'max_bin': 526, 'n_estimators': 1653, 'scale_pos_weight': 3.2848819311587154, 'min_child_weight': 3.0982512723205846, 'feature_fraction': 0.7786049991397331, 'bagging_fraction': 0.5409850381444363, 'bagging_freq': 2}

import lightgbm as lgb
model_1 = lgb.LGBMClassifier(**param_1, random_state=RANDOM_STATE, n_jobs=-1)
model_2 = lgb.LGBMClassifier(**param_2, random_state=RANDOM_STATE, n_jobs=-1)
model_3 = lgb.LGBMClassifier(**param_3, random_state=RANDOM_STATE, n_jobs=-1)

model_1.fit(X, y)
model_2.fit(X, y)
model_3.fit(X, y)

model_1_pred = model_1.predict_proba(test_encoded)[:, 1]
model_2_pred = model_2.predict_proba(test_encoded)[:, 1]
model_3_pred = model_3.predict_proba(test_encoded)[:, 1]

ensemble_pred = (model_1_pred + model_2_pred + model_3_pred) / 3

In [53]:
sample_submission = pd.read_csv('./data/sample_submission.csv')
sample_submission['probability'] = ensemble_pred

# temp_list = ['난자 저장용',  '기증용']
# # '기증용, 배아 저장용'
# sample_submission.loc[test[test['배아 생성 주요 이유'].isin(temp_list)].index, 'probability'] = 0
sample_submission.loc[test[test['시술 당시 나이'] == -1].index, 'probability'] = 0

sample_submission.to_csv('./data/튜닝_안나누기_단일_후처리_랜덤수정_350_앙상블.csv', index=False)