# 기본 설정

라이브러리 import

In [ ]:
# 기본 라이브러리
import os
import random
import numpy as np
import pandas as pd
import re
import torch
# 모델 및 평가 관련 라이브러리
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import roc_auc_score

# 데이터 불균형 처리 라이브러리
from imblearn.over_sampling import SMOTE, RandomOverSampler
from collections import Counter

# 하이퍼파라미터 최적화 및 전처리
import optuna
from sklearn.preprocessing import OneHotEncoder

# 경고 무시 설정
import warnings
warnings.filterwarnings("ignore")

c:\Users\user\anaconda3\envs\py_39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

라이브러리 버전 확인

In [1]:
import os
import random
import numpy as np
import pandas as pd
import torch
import sklearn
import imblearn
import optuna
import re
import sys

print("OS:", os.name) # 윈도우 OS 사용
print("Python version:", sys.version)
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("PyTorch:", torch.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Imbalanced-learn:", imblearn.__version__)
print("Optuna:", optuna.__version__)
print("re:", re.__version__)

OS: nt
Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:39:05) [MSC v.1929 64 bit (AMD64)]
NumPy: 1.26.4
Pandas: 2.2.3
PyTorch: 2.5.1
Scikit-learn: 1.1.3
Imbalanced-learn: 0.12.4
Optuna: 4.2.1
re: 2.2.1

c:\Users\user\anaconda3\envs\py_39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

랜덤시드 고정

In [2]:
RANDOM_STATE = 736665
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(RANDOM_STATE)

seed_everything(RANDOM_STATE)

## 데이터 불러오기

In [5]:
train = pd.read_csv('./data/train.csv').drop(columns=['ID'])
test = pd.read_csv('./data/test.csv').drop(columns=['ID'])
print(train.shape, test.shape)
train.head()

(256351, 68) (90067, 67)

,시술 시기 코드,시술 당시 나이,임신 시도 또는 마지막 임신 경과 연수,시술 유형,특정 시술 유형,배란 자극 여부,배란 유도 유형,단일 배아 이식 여부,착상 전 유전 검사 사용 여부,착상 전 유전 진단 사용 여부,...,기증 배아 사용 여부,대리모 여부,PGD 시술 여부,PGS 시술 여부,난자 채취 경과일,난자 해동 경과일,난자 혼합 경과일,배아 이식 경과일,배아 해동 경과일,임신 성공 여부
0,TRZKPL,만18-34세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,0.0,...,0.0,0.0,NaN,NaN,0.0,NaN,0.0,3.0,NaN,0
1,TRYBLT,만45-50세,NaN,IVF,ICSI,0,알 수 없음,0.0,NaN,0.0,...,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0
2,TRVNRY,만18-34세,NaN,IVF,IVF,1,기록되지 않은 시행,0.0,NaN,0.0,...,0.0,0.0,NaN,NaN,0.0,NaN,0.0,2.0,NaN,0
3,TRJXFG,만35-37세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,0.0,...,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0
4,TRVNRY,만18-34세,NaN,IVF,ICSI,1,기록되지 않은 시행,0.0,NaN,0.0,...,0.0,0.0,NaN,NaN,0.0,NaN,0.0,3.0,NaN,0

In [6]:
train['임신 성공 여부'].value_counts()

임신 성공 여부
0    190123
1     66228
Name: count, dtype: int64

# 데이터 전처리

In [5]:
# 한 컬럼에 값이 하나이며 결측치가 없는 열 제거
del_col = []
for col in train.columns:
    if train[col].nunique() == 1:
        if train[col].isnull().sum() == 0:
            print(train[col].value_counts())
            print('결측치 개수 :', train[col].isnull().sum())
            del_col.append(col)
del_col

불임 원인 - 여성 요인
0    256351
Name: count, dtype: int64
결측치 개수 : 0

['불임 원인 - 여성 요인']

In [6]:
# 전부 결측치인 열 제거 
for col in train.columns:
    if train[col].notnull().sum() == 0:
        del_col.append(col)
del_col

['불임 원인 - 여성 요인']

In [7]:
train.drop(columns=del_col, inplace=True)
test.drop(columns=del_col, inplace=True)
train.shape, test.shape

((256351, 67), (90067, 66))

### 결측치 처리

In [8]:
temp = pd.DataFrame(train.isnull().sum(), columns=['결측치 개수'])
temp = temp[temp['결측치 개수'] > 0]
temp['결측치 비율'] = temp['결측치 개수'] / train.shape[0] * 100
temp

                       결측치 개수     결측치 비율
임신 시도 또는 마지막 임신 경과 연수  246981  96.344855
특정 시술 유형                    2   0.000780
단일 배아 이식 여부              6291   2.454057
착상 전 유전 검사 사용 여부       253633  98.939735
착상 전 유전 진단 사용 여부         6291   2.454057
배아 생성 주요 이유              6291   2.454057
총 생성 배아 수                6291   2.454057
미세주입된 난자 수               6291   2.454057
미세주입에서 생성된 배아 수          6291   2.454057
이식된 배아 수                 6291   2.454057
미세주입 배아 이식 수             6291   2.454057
저장된 배아 수                 6291   2.454057
미세주입 후 저장된 배아 수          6291   2.454057
해동된 배아 수                 6291   2.454057
해동 난자 수                  6291   2.454057
수집된 신선 난자 수              6291   2.454057
저장된 신선 난자 수              6291   2.454057
혼합된 난자 수                 6291   2.454057
파트너 정자와 혼합된 난자 수         6291   2.454057
기증자 정자와 혼합된 난자 수         6291   2.454057
동결 배아 사용 여부              6291   2.454057
신선 배아 사용 여부              6291   2.454057
기증 배아 사용 여부              6291   2.454057
대리모 여부                   6291   2.454057
PGD 시술 여부              254172  99.149994
PGS 시술 여부              254422  99.247516
난자 채취 경과일               57488  22.425503
난자 해동 경과일              254915  99.439831
난자 혼합 경과일               53735  20.961494
배아 이식 경과일               43566  16.994667
배아 해동 경과일              215982  84.252451

In [9]:
## 결측치 처리
to_zero_columns = []
train[to_zero_columns] = train[to_zero_columns].fillna(0)
test[to_zero_columns] = test[to_zero_columns].fillna(0)


to_minus_columns = ['난자 채취 경과일']
train[to_minus_columns] = train[to_minus_columns].fillna(-1)
test[to_minus_columns] = test[to_minus_columns].fillna(-1)


to_one_columns = []
train[to_one_columns] = train[to_one_columns].fillna(1)
test[to_one_columns] = test[to_one_columns].fillna(1)


to_drop_columns = ['임신 시도 또는 마지막 임신 경과 연수', '난자 해동 경과일', '배아 해동 경과일']
train = train.drop(columns=to_drop_columns)
test = test.drop(columns=to_drop_columns)

to_mean_columns = ['배아 이식 경과일', '난자 혼합 경과일']
train[to_mean_columns] = train[to_mean_columns].fillna(train[to_mean_columns].mean())
test[to_mean_columns] = test[to_mean_columns].fillna(train[to_mean_columns].mean())


train['특정 시술 유형'].fillna(train['특정 시술 유형'].value_counts().index[0], inplace=True)
test['특정 시술 유형'].fillna(train['특정 시술 유형'].value_counts().index[0], inplace=True)

train.isnull().sum().sum(), test.isnull().sum().sum()

(894338, 313512)

In [10]:
# PGD 시술 여부 또는 PGS 시술 여부가 1이면 착상 전 유전 검사 사용 여부도 1로 설정하는 함수
def update_preimplantation_testing(df):
    df.loc[(df["착상 전 유전 진단 사용 여부"] == 1), "PGD 시술 여부"] = 1
    df.loc[(df["PGD 시술 여부"] == 1), "착상 전 유전 진단 사용 여부"] = 1
    df.loc[((df["착상 전 유전 검사 사용 여부"] == 1) & (df["PGD 시술 여부"].isna())), "PGS 시술 여부"] = 1
    return df

# train 및 test 데이터프레임 전처리 적용
train = update_preimplantation_testing(train)
test = update_preimplantation_testing(test)
train.isnull().sum().sum(), test.isnull().sum().sum()

(892558, 312901)

In [11]:
temp = pd.DataFrame(train.isnull().sum(), columns=['결측치 개수'])
temp = temp[temp['결측치 개수'] > 0]
temp['결측치 비율'] = temp['결측치 개수'] / train.shape[0] * 100
temp

                  결측치 개수     결측치 비율
단일 배아 이식 여부         6291   2.454057
착상 전 유전 검사 사용 여부  253633  98.939735
착상 전 유전 진단 사용 여부    6291   2.454057
배아 생성 주요 이유         6291   2.454057
총 생성 배아 수           6291   2.454057
미세주입된 난자 수          6291   2.454057
미세주입에서 생성된 배아 수     6291   2.454057
이식된 배아 수            6291   2.454057
미세주입 배아 이식 수        6291   2.454057
저장된 배아 수            6291   2.454057
미세주입 후 저장된 배아 수     6291   2.454057
해동된 배아 수            6291   2.454057
해동 난자 수             6291   2.454057
수집된 신선 난자 수         6291   2.454057
저장된 신선 난자 수         6291   2.454057
혼합된 난자 수            6291   2.454057
파트너 정자와 혼합된 난자 수    6291   2.454057
기증자 정자와 혼합된 난자 수    6291   2.454057
동결 배아 사용 여부         6291   2.454057
신선 배아 사용 여부         6291   2.454057
기증 배아 사용 여부         6291   2.454057
대리모 여부              6291   2.454057
PGD 시술 여부         253155  98.753272
PGS 시술 여부         253659  98.949877

In [12]:
# 시술 유형이 DI라서 생기는 결측치 따로 처리
print(temp[temp['결측치 개수'] == 6291].index)
for col in temp[temp['결측치 개수'] == 6291].index:
    if train[col].dtype == 'object':
        train[col].fillna('DI_알 수 없음', inplace=True)
        test[col].fillna('DI_알 수 없음', inplace=True)

    elif train[col].nunique() == 2:
        train[col].fillna(train[col].mode()[0], inplace=True)
        test[col].fillna(train[col].mode()[0], inplace=True)

    else:
        train[col] = train[col].fillna(train[col].mean())
        test[col] = test[col].fillna(train[col].mean())
        
train.isnull().sum().sum(), test.isnull().sum().sum()

Index(['단일 배아 이식 여부', '착상 전 유전 진단 사용 여부', '배아 생성 주요 이유', '총 생성 배아 수',
       '미세주입된 난자 수', '미세주입에서 생성된 배아 수', '이식된 배아 수', '미세주입 배아 이식 수', '저장된 배아 수',
       '미세주입 후 저장된 배아 수', '해동된 배아 수', '해동 난자 수', '수집된 신선 난자 수', '저장된 신선 난자 수',
       '혼합된 난자 수', '파트너 정자와 혼합된 난자 수', '기증자 정자와 혼합된 난자 수', '동결 배아 사용 여부',
       '신선 배아 사용 여부', '기증 배아 사용 여부', '대리모 여부'],
      dtype='object')

(760447, 267205)

In [13]:
to_drop_columns = ['착상 전 유전 검사 사용 여부', 'PGD 시술 여부', 'PGS 시술 여부']
train = train.drop(columns=to_drop_columns)
test = test.drop(columns=to_drop_columns)
train.isnull().sum().sum(), test.isnull().sum().sum()

(0, 0)

### 범주형 변수 인코딩

In [ ]:
convert_dict1 = {'0회': 0, '1회': 1, '2회': 2, '3회': 3, '4회': 4, '5회': 5, '6회 이상': 6}

# 변환할 컬럼 리스트
columns_to_convert1 = [
    "총 시술 횟수", "클리닉 내 총 시술 횟수", "IVF 시술 횟수", "DI 시술 횟수",
    "총 임신 횟수", "IVF 임신 횟수", "DI 임신 횟수",
    "총 출산 횟수", "IVF 출산 횟수", "DI 출산 횟수"]

# 변환 딕셔너리 생성
convert_dict2 = {'만18-34세' : 26, '만35-37세' : 36, '만38-39세' : 39, '만40-42세' : 41, '만43-44세' : 44,
                 '만45-50세' : 48, '알 수 없음' : -1}

# 변환할 컬럼 리스트
columns_to_convert2 = ["시술 당시 나이"]

convert_dict3 = {'만20세 이하' : 20, '만21-25세' : 23, '만26-30세' : 28, '만31-35세' : 33,
                 '만36-40세' : 38, '만41-45세' : 43, '알 수 없음' : -1}

# 변환할 컬럼 리스트
columns_to_convert3 = ["난자 기증자 나이", "정자 기증자 나이"]

In [14]:
train[columns_to_convert1] = train[columns_to_convert1].replace(convert_dict1)
test[columns_to_convert1] = test[columns_to_convert1].replace(convert_dict1)

train[columns_to_convert2] = train[columns_to_convert2].replace(convert_dict2)
test[columns_to_convert2] = test[columns_to_convert2].replace(convert_dict2)

train[columns_to_convert3] = train[columns_to_convert3].replace(convert_dict3)
test[columns_to_convert3] = test[columns_to_convert3].replace(convert_dict3)

In [15]:
categorical_columns = train.select_dtypes(include='object').columns
categorical_columns

Index(['시술 시기 코드', '시술 유형', '특정 시술 유형', '배란 유도 유형', '배아 생성 주요 이유', '난자 출처',
       '정자 출처'],
      dtype='object')

In [ ]:
onehot_encoder = OneHotEncoder(handle_unknown='ignore')
train_encoded = train.copy()
test_encoded = test.copy()

# 원핫 인코딩 적용
train_encoded_array = onehot_encoder.fit_transform(train[categorical_columns])
test_encoded_array = onehot_encoder.transform(test[categorical_columns])

# 새로운 DataFrame으로 변환
train_encoded_df = pd.DataFrame(train_encoded_array.toarray(), columns=onehot_encoder.get_feature_names_out(categorical_columns), index=train.index) # Changed to toarray()
test_encoded_df = pd.DataFrame(test_encoded_array.toarray(), columns=onehot_encoder.get_feature_names_out(categorical_columns), index=test.index) # Changed to toarray()

# 기존 데이터에서 범주형 컬럼 제거 후 원핫 인코딩된 데이터 추가
train_encoded = train.drop(columns=categorical_columns).join(train_encoded_df)
test_encoded = test.drop(columns=categorical_columns).join(test_encoded_df)
train_encoded.shape, test_encoded.shape

((256351, 112), (90067, 111))

In [ ]:
# 컬럼명 오류 안나도록 변경
train_encoded.columns = [re.sub(r'[^\w\s]', '_', col) for col in train_encoded.columns]
test_encoded.columns = [re.sub(r'[^\w\s]', '_', col) for col in test_encoded.columns]

# 모델링

### 샘플링 실험

In [19]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

# train_data에서 임신 성공 여부을 제외한 모든 열을 feature로 사용
X = train_encoded.drop(columns=["임신 성공 여부"])
y = train_encoded["임신 성공 여부"]

# train 데이터를 5개로 나누어 교차 검증
under_ratio_df = pd.DataFrame(columns=["ratio", 'fold', "model", 'auc'])

ratio = 'default'
for i, index in enumerate(skf.split(X, y)):
    # 데이터 분할
    print(f"{ratio}, Fold {i + 1}")
    X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
    y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
    print(Counter(y_train), Counter(y_val))

    print('모델 학습 진행')
    class_counts = Counter(y_train)
    negative_count = class_counts[0]  # 음성 클래스 (보통 0)
    positive_count = class_counts[1]  # 양성 클래스 (보통 1)

    # 클래스 불균형 비율 계산
    class_imbalance_ratio = negative_count / positive_count if positive_count > 0 else 1
    import xgboost as xgb
    import lightgbm as lgb
    import catboost as cat
    xgb = xgb.XGBClassifier(random_state=RANDOM_STATE, scale_pos_weight=class_imbalance_ratio)
    lgbm = lgb.LGBMClassifier(random_state=RANDOM_STATE, is_unbalance=True, verbose=-1)
    cat = cat.CatBoostClassifier(verbose=0, random_state=RANDOM_STATE, auto_class_weights="Balanced")
    for model in [xgb, lgbm, cat]:
        print(model.__class__.__name__)
        model.fit(X_train, y_train)

        y_proba = model.predict_proba(X_val)[:, 1]
        auc = roc_auc_score(y_val, y_proba)

        under_ratio_df.loc[len(under_ratio_df), :] = [ratio, i+1, model.__class__.__name__, auc]

for ratio in range(1, 3):
    normal_ratio = ratio

    for i, index in enumerate(skf.split(X, y)):
        # 데이터 분할
        print(f"{ratio}, Fold {i + 1}")
        X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
        y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
        print(Counter(y_train), Counter(y_val))

        train = pd.concat([X_train, y_train], axis=1)
        val = pd.concat([X_val, y_val], axis=1)

        df_normal = train[train["임신 성공 여부"] == 0]
        df_abnormal = train[train["임신 성공 여부"] == 1]
        print(f"Total: Normal: {len(df_normal)}, AbNormal: {len(df_abnormal)}")

        df_normal = df_normal.sample(n=int(len(df_abnormal) * normal_ratio), replace=False, random_state=RANDOM_STATE)
        df_concat = pd.concat([df_normal, df_abnormal], axis=0).reset_index(drop=True)
        X_under, y_under = df_concat.drop(columns=["임신 성공 여부"]), df_concat["임신 성공 여부"]

        print("언더샘플링 후 train의 클래스 비율:", Counter(y_under))

        print('모델 학습 진행')
        class_counts = Counter(y_under)
        negative_count = class_counts[0]  # 음성 클래스 (보통 0)
        positive_count = class_counts[1]  # 양성 클래스 (보통 1)

        # 클래스 불균형 비율 계산
        class_imbalance_ratio = negative_count / positive_count if positive_count > 0 else 1
        import xgboost as xgb
        import lightgbm as lgb
        import catboost as cat
        xgb = xgb.XGBClassifier(random_state=RANDOM_STATE, scale_pos_weight=class_imbalance_ratio)
        lgbm = lgb.LGBMClassifier(random_state=RANDOM_STATE, is_unbalance=True, verbose=-1)
        cat = cat.CatBoostClassifier(verbose=0, random_state=RANDOM_STATE, auto_class_weights="Balanced")
        for model in [xgb, lgbm, cat]:
            print(model.__class__.__name__)
            model.fit(X_under, y_under)

            y_proba = model.predict_proba(X_val)[:, 1]
            auc = roc_auc_score(y_val, y_proba)
          
            under_ratio_df.loc[len(under_ratio_df), :] = [ratio, i+1, model.__class__.__name__, auc]


ratio = 'ros'
for i, index in enumerate(skf.split(X, y)):
    # 데이터 분할
    print(f"{ratio}, Fold {i + 1}")
    X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
    y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
    print(Counter(y_train), Counter(y_val))

    ros = RandomOverSampler(random_state=RANDOM_STATE)
    X_ros, y_ros = ros.fit_resample(X_train, y_train)
    print("Random Oversampling 클래스 비율:", Counter(y_ros))
    print('모델 학습 진행')
    class_counts = Counter(y_ros)
    negative_count = class_counts[0]  # 음성 클래스 (보통 0)
    positive_count = class_counts[1]  # 양성 클래스 (보통 1)

    # 클래스 불균형 비율 계산
    class_imbalance_ratio = negative_count / positive_count if positive_count > 0 else 1
    import xgboost as xgb
    import lightgbm as lgb
    import catboost as cat
    xgb = xgb.XGBClassifier(random_state=RANDOM_STATE, scale_pos_weight=class_imbalance_ratio)
    lgbm = lgb.LGBMClassifier(random_state=RANDOM_STATE, is_unbalance=True, verbose=-1)
    cat = cat.CatBoostClassifier(verbose=0, random_state=RANDOM_STATE, auto_class_weights="Balanced")

    for model in [xgb, lgbm, cat]:
        print(model.__class__.__name__)
        model.fit(X_ros, y_ros)

        y_proba = model.predict_proba(X_val)[:, 1]
        auc = roc_auc_score(y_val, y_proba)

        under_ratio_df.loc[len(under_ratio_df), :] = [ratio, i+1, model.__class__.__name__, auc]

default, Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
default, Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
default, Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
default, Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
default, Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
1, Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
Total: Normal: 152098, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 52982, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
1, Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Total: Normal: 152098, AbNormal: 52983
언더샘플링 후 train의 클래스 비율: Counter({0: 52983, 1: 52983})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
1, Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Total: Normal: 152098, AbNormal: 52983
언더샘플링 후 train의 클래스 비율: Counter({0: 52983, 1: 52983})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
1, Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Total: Normal: 152099, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 52982, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
1, Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Total: Normal: 152099, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 52982, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
2, Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
Total: Normal: 152098, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 105964, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
2, Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Total: Normal: 152098, AbNormal: 52983
언더샘플링 후 train의 클래스 비율: Counter({0: 105966, 1: 52983})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
2, Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Total: Normal: 152098, AbNormal: 52983
언더샘플링 후 train의 클래스 비율: Counter({0: 105966, 1: 52983})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
2, Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Total: Normal: 152099, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 105964, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
2, Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Total: Normal: 152099, AbNormal: 52982
언더샘플링 후 train의 클래스 비율: Counter({0: 105964, 1: 52982})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
ros, Fold 1
Counter({0: 152098, 1: 52982}) Counter({0: 38025, 1: 13246})
Random Oversampling 클래스 비율: Counter({0: 152098, 1: 152098})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
ros, Fold 2
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Random Oversampling 클래스 비율: Counter({0: 152098, 1: 152098})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
ros, Fold 3
Counter({0: 152098, 1: 52983}) Counter({0: 38025, 1: 13245})
Random Oversampling 클래스 비율: Counter({0: 152098, 1: 152098})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
ros, Fold 4
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Random Oversampling 클래스 비율: Counter({0: 152099, 1: 152099})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier
ros, Fold 5
Counter({0: 152099, 1: 52982}) Counter({0: 38024, 1: 13246})
Random Oversampling 클래스 비율: Counter({0: 152099, 1: 152099})
모델 학습 진행
XGBClassifier
LGBMClassifier
CatBoostClassifier

In [20]:
# 예측 알고리즘 별 k fold 성능
under_ratio_df.groupby(["ratio", "model"]).mean()[['auc']]

                                 auc
ratio   model
1       CatBoostClassifier  0.735787
        LGBMClassifier       0.73778
        XGBClassifier       0.733022
2       CatBoostClassifier  0.736441
        LGBMClassifier       0.73852
        XGBClassifier       0.734382
default CatBoostClassifier  0.736269
        LGBMClassifier      0.738864
        XGBClassifier       0.735134
ros     CatBoostClassifier  0.733794
        LGBMClassifier      0.738255
        XGBClassifier       0.734634

In [21]:
# 샘플링 별 k fold 성능
under_ratio_df.groupby(["ratio"])[['auc']].mean().sort_values(by='auc', ascending=False)

              auc
ratio
default  0.736756
2        0.736448
ros      0.735561
1         0.73553

In [22]:
# 성능 상위 5개 case 
top5_df = under_ratio_df.groupby(["ratio", "model"]).mean()[['auc']].sort_values(by='auc', ascending=False).head()
top5_df.reset_index(inplace=True)
top5_df

     ratio               model       auc
0  default      LGBMClassifier  0.738864
1        2      LGBMClassifier   0.73852
2      ros      LGBMClassifier  0.738255
3        1      LGBMClassifier   0.73778
4        2  CatBoostClassifier  0.736441

#### 하이퍼 파라미터 튜닝

optuna 적용

In [ ]:
X = train_encoded.drop(columns=["임신 성공 여부"])
y = train_encoded["임신 성공 여부"]

# Optuna objective 설정
def objective(trial, ratio, model_name):
    # k fold 교차 검증 -> optuna 자체의 cv 대신 사용 -> 샘플링 기법을 적용하기 위해서
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    
    auc_scores = []
    for index in skf.split(X, y):
        X_train, X_val = X.iloc[index[0]], X.iloc[index[1]]
        y_train, y_val = y.iloc[index[0]], y.iloc[index[1]]
        train = pd.concat([X_train, y_train], axis=1)

        # 샘플링 기법 적용
        if ratio == 'default':
            X_train_sample, y_train_sample = X_train, y_train

        elif ratio == 'ros':
            ros = RandomOverSampler(random_state=RANDOM_STATE)
            X_ros, y_ros = ros.fit_resample(X_train, y_train)
            X_train_sample, y_train_sample = X_ros, y_ros 

        elif ratio == 'smote':
            smote = SMOTE(sampling_strategy=0.7, random_state=RANDOM_STATE)
            X_smote, y_smote = smote.fit_resample(X_train, y_train)
            X_train_sample, y_train_sample = X_smote, y_smote

        else:
            normal_ratio = ratio
            df_normal = train[train["임신 성공 여부"] == 0]
            df_abnormal = train[train["임신 성공 여부"] == 1]

            df_normal = df_normal.sample(n=int(len(df_abnormal) * normal_ratio), replace=False, random_state=RANDOM_STATE)
            df_concat = pd.concat([df_normal, df_abnormal], axis=0).reset_index(drop=True)
            X_train_sample, y_train_sample = df_concat.drop(columns=["임신 성공 여부"]), df_concat["임신 성공 여부"]

        # 모델 별로 탐색 파라미터 지정
        if model_name == 'XGBClassifier':
            param = {
                'objective': 'binary:logistic',
                'eval_metric': 'auc',
                'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.1),  # 학습률 범위 좁힘
                'max_depth': trial.suggest_int('max_depth', 3, 7),  # max_depth 범위 좁힘
                'min_child_weight': trial.suggest_loguniform('min_child_weight', 1e-2, 5),  # 최소 가중치 범위 좁힘
                'subsample': trial.suggest_uniform('subsample', 0.6, 0.9),  # 샘플 비율 범위 좁힘
                'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 0.9),  # 특성 비율 범위 좁힘
                'lambda': trial.suggest_loguniform('lambda', 1e-3, 1.0),  # L2 정규화 범위 좁힘
                'alpha': trial.suggest_loguniform('alpha', 1e-3, 1.0),  # L1 정규화 범위 좁힘
                'n_estimators': trial.suggest_int('n_estimators', 500, 5000),
                'scale_pos_weight': trial.suggest_loguniform('scale_pos_weight', 1, 5),  # 불균형 클래스 가중치 범위 좁힘
                'gamma': trial.suggest_uniform('gamma', 0, 3),  # 트리 분할 시 최소 손실 감소값 범위 좁힘
                'max_delta_step': trial.suggest_int('max_delta_step', 0, 5)  # 과적합 방지 범위 좁힘
            }
            model = xgb.XGBClassifier(**param, random_state=RANDOM_STATE, n_jobs=-1)

        elif model_name == 'LGBMClassifier':
            param = {
                'objective': 'binary',
                'metric': 'auc',
                'learning_rate': trial.suggest_loguniform('learning_rate', 0.005, 0.1),  # 학습률 범위 확장
                'num_leaves': trial.suggest_int('num_leaves', 20, 80),  # num_leaves 범위 확장
                'max_depth': trial.suggest_int('max_depth', 3, 10),  # max_depth 범위 확장
                'min_child_samples': trial.suggest_int('min_child_samples', 10, 120),  # 최소 샘플 수 범위 확장
                'subsample': trial.suggest_uniform('subsample', 0.5, 1.0),  # 샘플링 비율 범위 확장
                'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.5, 1.0),  # 특성 비율 범위 확장
                'lambda_l1': trial.suggest_loguniform('lambda_l1', 1e-4, 10),  # L1 정규화 범위 확장
                'lambda_l2': trial.suggest_loguniform('lambda_l2', 1e-4, 2.0),  # L2 정규화 범위 확장
                'max_bin': trial.suggest_int('max_bin', 100, 600),  # bin 수 범위 확장
                'n_estimators': trial.suggest_int('n_estimators', 500, 6000),  # n_estimators 범위 확장
                'scale_pos_weight': trial.suggest_loguniform('scale_pos_weight', 0.5, 5),  # 클래스 불균형 조정
                'min_child_weight': trial.suggest_loguniform('min_child_weight', 1e-3, 5),  # 최소 가중치 범위 확장
                'feature_fraction': trial.suggest_uniform('feature_fraction', 0.5, 1.0),  # 특성 비율 범위 확장
                'bagging_fraction': trial.suggest_uniform('bagging_fraction', 0.5, 1.0),  # 배깅 샘플링 비율 범위 확장
                'bagging_freq': trial.suggest_int('bagging_freq', 1, 7)  # 배깅 적용 주기 범위 확장
            }
            model = lgb.LGBMClassifier(**param, random_state=RANDOM_STATE, n_jobs=-1)
            
        elif model_name == 'CatBoostClassifier':
            param = {
                'objective': 'Logloss',
                'eval_metric': 'AUC',
                'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.1),  # 학습률 범위 좁힘
                'depth': trial.suggest_int('depth', 3, 7),  # depth 범위 좁힘
                'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 5.0),  # L2 정규화 범위 좁힘
                'random_strength': trial.suggest_uniform('random_strength', 0.5, 3),  # 잡음 정도 범위 좁힘
                'bagging_temperature': trial.suggest_uniform('bagging_temperature', 0, 0.3),  # 배깅 온도 범위 좁힘
                # 'border_count': trial.suggest_int('border_count', 32, 100),  # border 수 범위 좁힘
                'colsample_bylevel': trial.suggest_uniform('colsample_bylevel', 0.6, 0.9),  # 특성 비율 범위 좁힘
                'iterations': trial.suggest_int('iterations', 500, 2000),
                # 'scale_pos_weight': trial.suggest_loguniform('scale_pos_weight', 1, 5),  # 불균형 클래스 가중치 범위 좁힘
                'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 50),  # 리프 노드 최소 데이터 수 범위 좁힘
                'max_bin': trial.suggest_int('max_bin', 100, 150)  # bin 수 범위 좁힘
            }
            model = cat.CatBoostClassifier(**param, verbose=0, random_state=RANDOM_STATE, auto_class_weights="Balanced")    

        else:
            raise ValueError("Invalid model name")
        model.fit(X_train_sample, y_train_sample)

        # 예측 및 AUC 평가
        y_prob = model.predict_proba(X_val)[:, 1]  # 클래스 1의 확률 예측
        auc = roc_auc_score(y_val, y_prob)
        auc_scores.append(auc)

    # 평균 AUC 반환 (Optuna는 최대화 목표)
    return np.mean(auc_scores)

In [ ]:
# 최적화 함수 정의
def optimize_ran(ratio, model_name):
    def objective_wrapper(trial):
        return objective(trial, ratio, model_name)
    
    # **초반에는 RandomSampler 사용 (빠른 탐색)**
    study = optuna.create_study(
        direction='maximize', 
        sampler=optuna.samplers.RandomSampler(seed=RANDOM_STATE)  # 랜덤 샘플링 시드 고정
    )
    study.optimize(objective_wrapper, n_trials=30)  # 초반 30회 랜덤 탐색

    # **이후 TPESampler로 변경 (정밀 탐색)**
    study.sampler = optuna.samplers.TPESampler(seed=RANDOM_STATE)  # TPESampler 시드 고정
    study.optimize(objective_wrapper, n_trials=100)  # 추가 100회 정밀 탐색

    print('Best hyperparameters: ', study.best_params, study.best_value)
    return study.best_params, study.best_value

# optuna 진행
params, auc, study = optimize_ran(ratio=top5_df['ratio'][0], model_name=top5_df['model'][0])
top5_df.loc[0, ['param', 'tuned_auc']] =  params, auc

[I 2025-02-24 01:48:00,501] A new study created in memory with name: no-name-3e2f1f9e-0b61-42b6-a022-c99f45d969d8

0

[I 2025-02-24 01:51:04,382] Trial 0 finished with value: 0.7341495983239276 and parameters: {'learning_rate': 0.015425143772139221, 'num_leaves': 66, 'max_depth': 9, 'min_child_samples': 106, 'subsample': 0.8653901486840079, 'colsample_bytree': 0.9983917544473779, 'lambda_l1': 0.6105295749847629, 'lambda_l2': 0.044168222863989644, 'max_bin': 126, 'n_estimators': 2273, 'scale_pos_weight': 1.95333788496361, 'min_child_weight': 0.05291362037823648, 'feature_fraction': 0.9523240386576735, 'bagging_fraction': 0.6518583351261913, 'bagging_freq': 7}. Best is trial 0 with value: 0.7341495983239276.
[I 2025-02-24 01:53:50,136] Trial 1 finished with value: 0.7339573104868691 and parameters: {'learning_rate': 0.03116375846521187, 'num_leaves': 30, 'max_depth': 10, 'min_child_samples': 46, 'subsample': 0.7221916135181802, 'colsample_bytree': 0.7974033679912669, 'lambda_l1': 0.009015009783863792, 'lambda_l2': 0.22318604907203787, 'max_bin': 309, 'n_estimators': 3278, 'scale_pos_weight': 1.1584740056323315, 'min_child_weight': 0.001135663095613767, 'feature_fraction': 0.712712879854045, 'bagging_fraction': 0.9033154902029454, 'bagging_freq': 5}. Best is trial 0 with value: 0.7341495983239276.
[I 2025-02-24 01:57:16,176] Trial 2 finished with value: 0.739879951170409 and parameters: {'learning_rate': 0.005585138038286644, 'num_leaves': 30, 'max_depth': 9, 'min_child_samples': 17, 'subsample': 0.5716200252264407, 'colsample_bytree': 0.5563822503362531, 'lambda_l1': 0.37445243392490873, 'lambda_l2': 0.03917400861968649, 'max_bin': 168, 'n_estimators': 3134, 'scale_pos_weight': 1.3761192208957074, 'min_child_weight': 0.0014322261738596, 'feature_fraction': 0.5709073409709251, 'bagging_fraction': 0.6368713177073566, 'bagging_freq': 6}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 01:58:35,836] Trial 3 finished with value: 0.7394856733576038 and parameters: {'learning_rate': 0.008096960834540465, 'num_leaves': 71, 'max_depth': 7, 'min_child_samples': 111, 'subsample': 0.6859298884663338, 'colsample_bytree': 0.6141613195771627, 'lambda_l1': 1.108795846523692, 'lambda_l2': 0.7882677565739042, 'max_bin': 541, 'n_estimators': 1340, 'scale_pos_weight': 4.668696941089527, 'min_child_weight': 0.3095631848544191, 'feature_fraction': 0.7817151315868243, 'bagging_fraction': 0.8898762895296095, 'bagging_freq': 1}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 01:59:20,077] Trial 4 finished with value: 0.7337774720117548 and parameters: {'learning_rate': 0.09990956777240707, 'num_leaves': 22, 'max_depth': 9, 'min_child_samples': 91, 'subsample': 0.9551760582624331, 'colsample_bytree': 0.6872439089217708, 'lambda_l1': 1.2635997976483877, 'lambda_l2': 0.24901720148451442, 'max_bin': 262, 'n_estimators': 881, 'scale_pos_weight': 3.3053781683280863, 'min_child_weight': 0.00602996638950076, 'feature_fraction': 0.6903408973729224, 'bagging_fraction': 0.5789881028586417, 'bagging_freq': 2}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:02:32,282] Trial 5 finished with value: 0.7258640042077529 and parameters: {'learning_rate': 0.07347180751475983, 'num_leaves': 78, 'max_depth': 5, 'min_child_samples': 39, 'subsample': 0.6462960279748633, 'colsample_bytree': 0.9029742680124451, 'lambda_l1': 1.6452578296693248, 'lambda_l2': 0.2166297935943999, 'max_bin': 116, 'n_estimators': 4162, 'scale_pos_weight': 0.8034355990112857, 'min_child_weight': 0.015629967337268454, 'feature_fraction': 0.704909834669965, 'bagging_fraction': 0.7767297049533608, 'bagging_freq': 7}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:07:54,411] Trial 6 finished with value: 0.738129509397681 and parameters: {'learning_rate': 0.007055958592362742, 'num_leaves': 75, 'max_depth': 6, 'min_child_samples': 59, 'subsample': 0.7868548396950638, 'colsample_bytree': 0.9661174751955484, 'lambda_l1': 7.510380211774199, 'lambda_l2': 0.001082515878269277, 'max_bin': 205, 'n_estimators': 5302, 'scale_pos_weight': 1.36889391346348, 'min_child_weight': 0.27082904763757115, 'feature_fraction': 0.9115005320221202, 'bagging_fraction': 0.6338247134014405, 'bagging_freq': 4}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:09:11,294] Trial 7 finished with value: 0.7362315764413877 and parameters: {'learning_rate': 0.05038051650808287, 'num_leaves': 38, 'max_depth': 5, 'min_child_samples': 93, 'subsample': 0.881223407910463, 'colsample_bytree': 0.5327622162515878, 'lambda_l1': 0.4894064145453653, 'lambda_l2': 0.012043010609013723, 'max_bin': 259, 'n_estimators': 1523, 'scale_pos_weight': 2.0812420732908947, 'min_child_weight': 0.0016081892341730456, 'feature_fraction': 0.7842528265669715, 'bagging_fraction': 0.7462220377237454, 'bagging_freq': 3}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:16:41,049] Trial 8 finished with value: 0.708110385978969 and parameters: {'learning_rate': 0.06885482660033462, 'num_leaves': 75, 'max_depth': 10, 'min_child_samples': 19, 'subsample': 0.9069891313342352, 'colsample_bytree': 0.6153416039231351, 'lambda_l1': 3.510360536810731, 'lambda_l2': 0.006172259803263764, 'max_bin': 577, 'n_estimators': 4910, 'scale_pos_weight': 2.3375765118714305, 'min_child_weight': 0.06967565185933576, 'feature_fraction': 0.551697668559838, 'bagging_fraction': 0.8555369001730506, 'bagging_freq': 5}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:17:52,522] Trial 9 finished with value: 0.7393593898154146 and parameters: {'learning_rate': 0.00636669956943231, 'num_leaves': 44, 'max_depth': 5, 'min_child_samples': 44, 'subsample': 0.6076315564100284, 'colsample_bytree': 0.8493410264545999, 'lambda_l1': 0.24503195253374185, 'lambda_l2': 0.15906650264278605, 'max_bin': 106, 'n_estimators': 1710, 'scale_pos_weight': 0.5689494137118395, 'min_child_weight': 0.11526044723423878, 'feature_fraction': 0.6387935121225002, 'bagging_fraction': 0.996860792879829, 'bagging_freq': 1}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:18:52,080] Trial 10 finished with value: 0.7398149316309942 and parameters: {'learning_rate': 0.009472902001113578, 'num_leaves': 44, 'max_depth': 4, 'min_child_samples': 78, 'subsample': 0.9263304974726281, 'colsample_bytree': 0.9545125683629523, 'lambda_l1': 0.003983286973198198, 'lambda_l2': 0.07408975311080031, 'max_bin': 211, 'n_estimators': 1731, 'scale_pos_weight': 2.160158734295782, 'min_child_weight': 1.7815490358345771, 'feature_fraction': 0.9178770758397096, 'bagging_fraction': 0.5337384100461013, 'bagging_freq': 7}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:20:11,923] Trial 11 finished with value: 0.7363132465992359 and parameters: {'learning_rate': 0.05058616696034423, 'num_leaves': 29, 'max_depth': 6, 'min_child_samples': 22, 'subsample': 0.6584970207947708, 'colsample_bytree': 0.535131601120893, 'lambda_l1': 0.001935483655522908, 'lambda_l2': 0.003266184011866186, 'max_bin': 281, 'n_estimators': 1295, 'scale_pos_weight': 0.8363173112229804, 'min_child_weight': 0.0020073395997213016, 'feature_fraction': 0.8102603222555723, 'bagging_fraction': 0.9593265845263816, 'bagging_freq': 2}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:21:37,621] Trial 12 finished with value: 0.7392919531869688 and parameters: {'learning_rate': 0.03507053331232095, 'num_leaves': 43, 'max_depth': 3, 'min_child_samples': 89, 'subsample': 0.5643007988281081, 'colsample_bytree': 0.7507367701850713, 'lambda_l1': 0.0026815604808119843, 'lambda_l2': 0.04057493655651061, 'max_bin': 290, 'n_estimators': 2475, 'scale_pos_weight': 1.5926206056622803, 'min_child_weight': 0.003797772466909962, 'feature_fraction': 0.7219512472304341, 'bagging_fraction': 0.7159709268191258, 'bagging_freq': 4}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:24:27,288] Trial 13 finished with value: 0.7308075225242163 and parameters: {'learning_rate': 0.05442765462289306, 'num_leaves': 24, 'max_depth': 6, 'min_child_samples': 108, 'subsample': 0.724748777973639, 'colsample_bytree': 0.782683685963973, 'lambda_l1': 0.005871204131712403, 'lambda_l2': 0.0018639154247633543, 'max_bin': 448, 'n_estimators': 2995, 'scale_pos_weight': 1.7360946109753392, 'min_child_weight': 0.0011631477719490774, 'feature_fraction': 0.6315332289456946, 'bagging_fraction': 0.7299133053657518, 'bagging_freq': 2}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:30:44,546] Trial 14 finished with value: 0.7363412638454028 and parameters: {'learning_rate': 0.007698903333238432, 'num_leaves': 66, 'max_depth': 8, 'min_child_samples': 40, 'subsample': 0.91959244871182, 'colsample_bytree': 0.7420988472180625, 'lambda_l1': 0.00103002762919727, 'lambda_l2': 0.0003491098245162472, 'max_bin': 288, 'n_estimators': 4429, 'scale_pos_weight': 0.7362551960843415, 'min_child_weight': 0.10525773369069878, 'feature_fraction': 0.9344325613802366, 'bagging_fraction': 0.983452210859086, 'bagging_freq': 2}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:33:49,286] Trial 15 finished with value: 0.7313062719492536 and parameters: {'learning_rate': 0.07088890582916445, 'num_leaves': 52, 'max_depth': 4, 'min_child_samples': 109, 'subsample': 0.6367319035708044, 'colsample_bytree': 0.9353686317549218, 'lambda_l1': 0.0007718539662243672, 'lambda_l2': 0.001107228041242988, 'max_bin': 298, 'n_estimators': 4742, 'scale_pos_weight': 1.9304861367099717, 'min_child_weight': 0.00433391002815958, 'feature_fraction': 0.7884565104762318, 'bagging_fraction': 0.9386320443689432, 'bagging_freq': 6}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:41:23,273] Trial 16 finished with value: 0.7300236931737277 and parameters: {'learning_rate': 0.012795921009748922, 'num_leaves': 72, 'max_depth': 8, 'min_child_samples': 29, 'subsample': 0.6001639397851228, 'colsample_bytree': 0.9198694088517618, 'lambda_l1': 2.6581833255133915, 'lambda_l2': 0.029317884958132864, 'max_bin': 115, 'n_estimators': 5263, 'scale_pos_weight': 0.9943338665426116, 'min_child_weight': 0.001825347991959572, 'feature_fraction': 0.9808177912972761, 'bagging_fraction': 0.6733017651978113, 'bagging_freq': 2}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:42:09,720] Trial 17 finished with value: 0.7384356184367737 and parameters: {'learning_rate': 0.019786597841588226, 'num_leaves': 43, 'max_depth': 7, 'min_child_samples': 17, 'subsample': 0.7167829217358992, 'colsample_bytree': 0.8153855730953183, 'lambda_l1': 0.08901114713196834, 'lambda_l2': 0.11475918106759839, 'max_bin': 184, 'n_estimators': 769, 'scale_pos_weight': 4.241550779708251, 'min_child_weight': 0.019463703782270116, 'feature_fraction': 0.9051864630110871, 'bagging_fraction': 0.5946442313411389, 'bagging_freq': 5}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:45:32,111] Trial 18 finished with value: 0.7289114314340376 and parameters: {'learning_rate': 0.06288155634331212, 'num_leaves': 21, 'max_depth': 5, 'min_child_samples': 119, 'subsample': 0.9019948650637313, 'colsample_bytree': 0.6996381302007002, 'lambda_l1': 0.33315171912427727, 'lambda_l2': 0.0020271308425866127, 'max_bin': 216, 'n_estimators': 4013, 'scale_pos_weight': 3.6976210284936233, 'min_child_weight': 1.283095233420513, 'feature_fraction': 0.6618374112414924, 'bagging_fraction': 0.7940054556087353, 'bagging_freq': 3}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:48:08,149] Trial 19 finished with value: 0.7319807579274316 and parameters: {'learning_rate': 0.03359729833812513, 'num_leaves': 66, 'max_depth': 10, 'min_child_samples': 38, 'subsample': 0.6830893045370803, 'colsample_bytree': 0.5293966377504692, 'lambda_l1': 0.07200906601313788, 'lambda_l2': 1.081709892322443, 'max_bin': 382, 'n_estimators': 1706, 'scale_pos_weight': 2.5954814796041226, 'min_child_weight': 0.017486270061591726, 'feature_fraction': 0.9178867323867471, 'bagging_fraction': 0.9537110904354152, 'bagging_freq': 2}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 02:55:09,046] Trial 20 finished with value: 0.7339152221173982 and parameters: {'learning_rate': 0.011345626605096769, 'num_leaves': 75, 'max_depth': 9, 'min_child_samples': 38, 'subsample': 0.9159144260138378, 'colsample_bytree': 0.5909900454472763, 'lambda_l1': 0.012880736066555386, 'lambda_l2': 0.0010195141515696757, 'max_bin': 256, 'n_estimators': 3230, 'scale_pos_weight': 3.4058426081316924, 'min_child_weight': 0.043935179376647635, 'feature_fraction': 0.9855540025756568, 'bagging_fraction': 0.9855584519671904, 'bagging_freq': 4}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:01:35,533] Trial 21 finished with value: 0.7080194328880124 and parameters: {'learning_rate': 0.044194419131192854, 'num_leaves': 58, 'max_depth': 10, 'min_child_samples': 30, 'subsample': 0.8471550516588009, 'colsample_bytree': 0.7672541724132067, 'lambda_l1': 0.019368913791820087, 'lambda_l2': 0.00011058211950156807, 'max_bin': 232, 'n_estimators': 5961, 'scale_pos_weight': 3.835921696908625, 'min_child_weight': 0.6027686909784113, 'feature_fraction': 0.7590792632633852, 'bagging_fraction': 0.6321388879355188, 'bagging_freq': 7}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:04:31,489] Trial 22 finished with value: 0.7243167626496912 and parameters: {'learning_rate': 0.08274408408082157, 'num_leaves': 37, 'max_depth': 5, 'min_child_samples': 84, 'subsample': 0.500538193404521, 'colsample_bytree': 0.7293722212316055, 'lambda_l1': 0.0006243741458877048, 'lambda_l2': 0.760408576569091, 'max_bin': 438, 'n_estimators': 3604, 'scale_pos_weight': 1.9298703331419969, 'min_child_weight': 0.0013805431275077543, 'feature_fraction': 0.948611595922684, 'bagging_fraction': 0.5983867067587514, 'bagging_freq': 6}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:07:30,407] Trial 23 finished with value: 0.7362559020366886 and parameters: {'learning_rate': 0.01917025199563695, 'num_leaves': 56, 'max_depth': 5, 'min_child_samples': 31, 'subsample': 0.6863174840785362, 'colsample_bytree': 0.6484642889031578, 'lambda_l1': 0.009294867312637456, 'lambda_l2': 0.016476513916362793, 'max_bin': 557, 'n_estimators': 3541, 'scale_pos_weight': 4.811064832170782, 'min_child_weight': 0.019542752600618694, 'feature_fraction': 0.8555266057879338, 'bagging_fraction': 0.742302555407246, 'bagging_freq': 3}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:11:12,281] Trial 24 finished with value: 0.7378696211044167 and parameters: {'learning_rate': 0.016092824205502492, 'num_leaves': 36, 'max_depth': 4, 'min_child_samples': 13, 'subsample': 0.9756819114235328, 'colsample_bytree': 0.6607900788607213, 'lambda_l1': 0.08202750690104336, 'lambda_l2': 1.9899376558142507, 'max_bin': 367, 'n_estimators': 5449, 'scale_pos_weight': 3.2184823167162926, 'min_child_weight': 2.4948261886684224, 'feature_fraction': 0.8525644450191505, 'bagging_fraction': 0.9350941712527876, 'bagging_freq': 7}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:12:23,715] Trial 25 finished with value: 0.7357220824580025 and parameters: {'learning_rate': 0.04453108101502274, 'num_leaves': 21, 'max_depth': 7, 'min_child_samples': 76, 'subsample': 0.6727855762502507, 'colsample_bytree': 0.9764485815252452, 'lambda_l1': 0.028343288451527705, 'lambda_l2': 0.006068292762742412, 'max_bin': 273, 'n_estimators': 1653, 'scale_pos_weight': 4.828963400646951, 'min_child_weight': 0.004694980581985508, 'feature_fraction': 0.7492837420258035, 'bagging_fraction': 0.7093962705478856, 'bagging_freq': 7}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:15:50,437] Trial 26 finished with value: 0.72621903710169 and parameters: {'learning_rate': 0.0715445311961556, 'num_leaves': 32, 'max_depth': 5, 'min_child_samples': 35, 'subsample': 0.6031489153566904, 'colsample_bytree': 0.6193300563458408, 'lambda_l1': 0.020178354157555634, 'lambda_l2': 0.04510431019651522, 'max_bin': 237, 'n_estimators': 3436, 'scale_pos_weight': 2.4352554020456494, 'min_child_weight': 0.024498106082877665, 'feature_fraction': 0.985855061199002, 'bagging_fraction': 0.9046599056382517, 'bagging_freq': 2}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:19:42,120] Trial 27 finished with value: 0.73969803875184 and parameters: {'learning_rate': 0.005259047845727506, 'num_leaves': 20, 'max_depth': 3, 'min_child_samples': 90, 'subsample': 0.7551797664352489, 'colsample_bytree': 0.5129156297801307, 'lambda_l1': 0.0011826620675187561, 'lambda_l2': 0.03547199696039481, 'max_bin': 402, 'n_estimators': 5292, 'scale_pos_weight': 1.324502800720647, 'min_child_weight': 0.0015251378865179075, 'feature_fraction': 0.5913121419392753, 'bagging_fraction': 0.7715501355676715, 'bagging_freq': 3}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:25:56,953] Trial 28 finished with value: 0.7214064777652077 and parameters: {'learning_rate': 0.047616011810605104, 'num_leaves': 49, 'max_depth': 6, 'min_child_samples': 104, 'subsample': 0.9564851310444118, 'colsample_bytree': 0.5123181779086612, 'lambda_l1': 0.00010489822359226727, 'lambda_l2': 0.0005495206145623622, 'max_bin': 443, 'n_estimators': 5567, 'scale_pos_weight': 1.8896587886228244, 'min_child_weight': 0.0018480520436661473, 'feature_fraction': 0.6577089998732792, 'bagging_fraction': 0.5111975102027893, 'bagging_freq': 5}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:26:49,561] Trial 29 finished with value: 0.7398023456522185 and parameters: {'learning_rate': 0.016151559357501483, 'num_leaves': 25, 'max_depth': 7, 'min_child_samples': 20, 'subsample': 0.9087530112976543, 'colsample_bytree': 0.6125164462350836, 'lambda_l1': 0.027144085158493966, 'lambda_l2': 0.0004296915538823678, 'max_bin': 360, 'n_estimators': 780, 'scale_pos_weight': 0.8006892646103189, 'min_child_weight': 0.0318960228283267, 'feature_fraction': 0.6588687993237444, 'bagging_fraction': 0.5115602343350313, 'bagging_freq': 5}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:29:48,907] Trial 30 finished with value: 0.7396386169908765 and parameters: {'learning_rate': 0.009737866280708152, 'num_leaves': 26, 'max_depth': 8, 'min_child_samples': 55, 'subsample': 0.8251661577273887, 'colsample_bytree': 0.5743619983507836, 'lambda_l1': 0.14266860341558432, 'lambda_l2': 0.10396280057092915, 'max_bin': 162, 'n_estimators': 2334, 'scale_pos_weight': 0.5471773019621012, 'min_child_weight': 2.027173009119179, 'feature_fraction': 0.5153504019681332, 'bagging_fraction': 0.506655277555842, 'bagging_freq': 6}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:30:19,906] Trial 31 finished with value: 0.7329142563886495 and parameters: {'learning_rate': 0.006017717847563365, 'num_leaves': 27, 'max_depth': 3, 'min_child_samples': 72, 'subsample': 0.7886665923924627, 'colsample_bytree': 0.5652258544318806, 'lambda_l1': 0.0002509234327539, 'lambda_l2': 0.06209014651458907, 'max_bin': 332, 'n_estimators': 642, 'scale_pos_weight': 1.4037513673331774, 'min_child_weight': 4.063827568264329, 'feature_fraction': 0.5845007172995189, 'bagging_fraction': 0.5475842170035747, 'bagging_freq': 6}. Best is trial 2 with value: 0.739879951170409.
[I 2025-02-24 03:32:08,894] Trial 32 finished with value: 0.7391275080039521 and parameters: {'learning_rate': 0.005074414719605105, 'num_leaves': 31, 'max_depth': 4, 'min_child_samples': 72, 'subsample': 0.7809326240280882, 'colsample_bytree': 0.5606855094658154, 'lambda_l1': 0.003920828441867435, 'lambda_l2': 0.01404241907551949, 'max_bin': 400, 'n_estimators': 2065, 'scale_pos_weight': 1.098442035957651, 'min_child_weight': 0.009260810090148083, 'feature_fraction': 0.5999245266586377, 'bagging_fraction': 0.5494029266441746, 'bagging_freq': 6}. Best is trial 2 with value: 0.739879951170409.

Best hyperparameters:  {'learning_rate': 0.008826697606254305, 'num_leaves': 22, 'max_depth': 8, 'min_child_samples': 24, 'subsample': 0.5213248033529081, 'colsample_bytree': 0.588824074555704, 'lambda_l1': 5.592126646866256, 'lambda_l2': 0.001824157224218552, 'max_bin': 458, 'n_estimators': 1858, 'scale_pos_weight': 1.5152611515102326, 'min_child_weight': 1.6053944671635865, 'feature_fraction': 0.5339665006468401, 'bagging_fraction': 0.5627921003191587, 'bagging_freq': 3} 0.7401076532100873

In [35]:
top5_df

,ratio,model,auc,param,tuned_auc
0,default,LGBMClassifier,0.738864,"{'learning_rate': 0.008826697606254305, 'num_l...",0.740108
1,2,LGBMClassifier,0.73852,NaN,NaN
2,ros,LGBMClassifier,0.738255,NaN,NaN
3,1,LGBMClassifier,0.73778,NaN,NaN
4,2,CatBoostClassifier,0.736441,NaN,NaN

### 최종 예측

In [ ]:
# train_data에서 임신 성공 여부을 제외한 모든 열을 feature로 사용
X = train_encoded.drop(columns=["임신 성공 여부"])
y = train_encoded["임신 성공 여부"]

# 최적 샘플링 기법 선택
best_ratio = top5_df.loc[0, 'ratio']
print(best_ratio)
if best_ratio == 'default':
    X_sample, y_sample = X, y

elif best_ratio == 'ros':
    ros = RandomOverSampler(random_state=RANDOM_STATE)
    X_ros, y_ros = ros.fit_resample(X, y)
    print("Random Oversampling 클래스 비율:", Counter(y_ros))
    X_sample, y_sample = X_ros, y_ros 
else:
    normal_ratio = best_ratio
    df_normal = train_encoded[train_encoded["임신 성공 여부"] == 0]
    df_abnormal = train_encoded[train_encoded["임신 성공 여부"] == 1]
    print(f"Total: Normal: {len(df_normal)}, AbNormal: {len(df_abnormal)}")

    df_normal = df_normal.sample(n=int(len(df_abnormal) * normal_ratio), replace=False, random_state=RANDOM_STATE)
    df_concat = pd.concat([df_normal, df_abnormal], axis=0).reset_index(drop=True)
    X_sample, y_sample = df_concat.drop(columns=["임신 성공 여부"]), df_concat["임신 성공 여부"]

import xgboost as xgb
import lightgbm as lgb
import catboost as cat

# 최적 모델, 하이퍼 파라미터 선택
param = top5_df.loc[0, 'param']
if top5_df.loc[0, 'model'] == 'XGBClassifier':
    model = xgb.XGBClassifier(**param, random_state=RANDOM_STATE, n_jobs=-1)
elif top5_df.loc[0, 'model'] == 'LGBMClassifier':
    model = lgb.LGBMClassifier(**param, random_state=RANDOM_STATE, n_jobs=-1)
elif top5_df.loc[0, 'model'] == 'CatBoostClassifier':
    model =  cat.CatBoostClassifier(**param, random_state=RANDOM_STATE, auto_class_weights="Balanced")

model.fit(X_sample, y_sample)
test_proba = model.predict_proba(test_encoded)[:, 1]
test_proba

샘플링 진행
default

array([0.00255696, 0.00147716, 0.21474631, ..., 0.58934249, 0.28238356,
       0.00268898])

## 결과 저장

In [ ]:
sample_submission = pd.read_csv('./data/sample_submission.csv')
sample_submission['probability'] = test_proba

## 후처리

[train 데이터에 대해서]
- 시술 당시 나이가 '알 수 없음'이면 항상 '임신 성공 여부'는 0의 값을 가짐
- 배아 생성 주요 이유가 '난자 저장용', '기증용' 이면 항상 '임신 성공 여부'는 0의 값을 가짐

-> 따라서, 이 경우에 해당하는 최종 예측 확률값을 0으로 지정하는 후처리 진행

In [ ]:
temp_list = ['난자 저장용',  '기증용']
sample_submission.loc[test[test['배아 생성 주요 이유'].isin(temp_list)].index, 'probability'] = 0
sample_submission.loc[test[test['시술 당시 나이'] == -1].index, 'probability'] = 0
sample_submission.to_csv('./data/최종제출본.csv', index=False)